### ISSUE TITLE
High CPU usage after first connection

### ISSUE THREAD

**Issue by ThinkChaos** [tokio-rs/tokio-core#10]
On OS X (haven't tested anything else), as soon as a connection is opened, CPU usage climbs to 100%.

I can reproduce this using the echo server example and opening a connection using netcat.  
As soon as the connection is opened, the server uses 100% CPU until it is terminated (even after the netcat connection is closed).

**Comment by dwrensha** [comment]
I'm seeing the same problem, on OSX and Linux.

**Comment by alexcrichton** [comment]
Gah thanks for the report! Looks like fixing an unrelated bug led to this one... Should be fixed now though!
