### ISSUE TITLE
unresolved import?

### ISSUE THREAD

**Issue by colindjk** [tokio-rs/tokio-core#101]
Okay so I swear I'm not going crazy, but my compiler is giving me an unresolved import for Encode and Decode when I try

```rust
use tokio_core::io::{Decode, Encode};
```
then - "No `Decode` in tokio_core::io.

With my Cargo.toml
```rust
[dependencies]
futures = "0.1"
tokio-core = "0.1"

env_logger = "0.3"
```

I've had a lot of recent blockers, but this one takes the cake... and then some. Any idea what I could be doing wrong? That one-liner is literally what I had my main.rs comprised of (along with an extern crate tokio_core), just to make sure I wasn't losing it.

I also tried cleaning / removing Cargo.lock etc.

**Comment by colindjk** [comment]
Also, wanted to add that I can import everything except Encode and Decode.

**Comment by alexcrichton** [comment]
Oh one thing which may clarify this is that `Encode` and `Decode` haven't been published to crates.io just yet, they're only on the master branch. If you depend on the git versions though it should all work out!

**Comment by colindjk** [comment]
Oh thanks, figured it was... like that.

**Comment by alexcrichton** [comment]
Ok, closing!
