### ISSUE TITLE
Codec "encode" return value

### ISSUE THREAD

**Issue by colindjk** [tokio-rs/tokio-core#108]
Currently the encode function takes a buffer to write to as a parameter.

I was wondering if it would be possible to have the encode function return a result just as it did previously, prior to the Encode and Decode getting pushed into a unified Codec trait.

Unless of course there is justification, but I really wouldn't see one as the benefits of being able to notify the user of a failed "encode" would be real important.

**Comment by alexcrichton** [comment]
Hm I'm not sure that encode was able to ever signal an error, but it seems like an ok ability to me! Could you elaborate on the use case as well? Or do you think it should just return an `io::Result<()>`?

**Comment by colindjk** [comment]
Well yeah I was just thinking maybe an invalid character was given.

What I have now is a situation where I'm encoding a TCPStream into frames. The 'frames' are just JSON objects, so I encode the object into the said frame (JSON object). 

So there's the issue actually, in order to get that serialized info, I need to copy it into the buffer given by encode! (Yuck). That means serializing into a buffer, then copying that buffer data into a given buffer. To top it off, in order to serialize, I need to handle the possible errors inherent with the serialize functions.

Unfortunately though, the only way I can handle errors is by returning an empty array. Which then requires me to check the return value of encode so that the length of the array is not in fact zero.

Well jeepers, even writing that feels un-rust XD.

Anyway if it could just return io::Result<()> would be enough for me at least. There just needs to be something to pass up the error from whatever encoder I decide to use... I could make a pull request for ya :3.

**Comment by colindjk** [comment]
Oops ignore that first sentence it's not supposed to be there....
