### ISSUE TITLE
Setting timeouts with futures is not currently ergonomic

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#11]
From @nbigaouette in gitter

> I have a client that should attempt to connect to a remote server. How can I add a timeout to the connection attempt? I use `loop_handle.tcp_connect(addr)` which returns a future, but how can I insert my timeout? Using `select()`? `loop_handle.tcp_connect(addr).select(timeout)` where timeout comes from `loop_handle.clone().timeout(Duration::from_secs(5))` gives me a type mismatch `(tokio::Timeout vs tokio::TcpStream)`...

**Comment by nbigaouette** [comment]
Thanks. Here's the exact error:

```
   Compiling tokio_rogue v0.1.0 (file:///home/nbigaouette/tokio_client)
/home/nbigaouette/tokio_client/client.rs:40:10: 40:16 error: type mismatch resolving `<Box<futures::Future<Error=std::io::Error, Item=tokio::Timeout> + Send> as futures::IntoFuture>::Item == tokio::TcpStream`:
 expected struct `tokio::Timeout`,
    found struct `tokio::TcpStream` [E0271]
/home/nbigaouette/tokio_client/client.rs:40         .select(timeout_future)
                                                     ^~~~~~
/home/nbigaouette/tokio_client/client.rs:40:10: 40:16 help: run `rustc --explain E0271` to see a detailed explanation
```

Here's the code snippet:

```
pub fn connect(loop_handle: LoopHandle, addr: &SocketAddr, timeout: &Duration) -> IoFuture<Client> {
    println!("addr: {:?}", addr);
    // Create the timeout futures
    let timeout_future = loop_handle.clone().timeout(*timeout);
    // let timeout_future = loop_handle.clone().timeout(*timeout).and_then(|timeout| Err(Self::Error::from(timeout)));

    let h2 = loop_handle.clone();
    loop_handle.tcp_connect(addr)
        .select(timeout_future)
        .and_then(move |tcp| {
            let tcp = RefCell::new(Some(tcp));
            let c = pipeline::connect(h2, move || {
                // Not an ideal strategy, but fixing this requires some
                // upstream changes.
                let tcp = tcp.borrow_mut().take().unwrap();
                Ok(new_line_transport(tcp))
            });

            Ok(Client { inner: c })
        }).boxed()
}
```

Note that the `connect()` function comes from https://github.com/tokio-rs/tokio-line/blob/master/src/client.rs (c877b8c).

**Comment by tikue** [comment]
Could select allow any two types of futures to be selected on and wrap them in an enum?

**Comment by alexcrichton** [comment]
Ah yeah I think there's a few pieces in play here:
- First, creating a timeout returns a _future_ of the timeout itself. That timeout is then itself a future representing the timeout event.
- As @tikue mentioned, the `select` combinator requires the same type for each of the two futures being selected over. I typically `.map(Ok)` one of them and `.map(Err)` the timeout one.

**Comment by alexcrichton** [comment]
I believe this was made better with the 0.1 release which now returns `io::Result<Timeout>` from `Timeout::new` which doesn't have layers of futures. As a result I'm going to close, but I believe there's also work happening over with https://github.com/tokio-rs/tokio-timer for ergonomic timers!

**Comment by ArtemGr** [comment]
I'd gladly use the `tokio-timer` provided it could work with a shared `Core` instead of spawning a thread.
Right now it can't, so I've found myself making the following helper function.
Maybe it will inspire someone to write an ergonomic shared `Core` timeout helper in one of the Tokio libraries.

```
pub enum DueResult<R, E> {Ok (R), Err (E), Timeout, TimeoutErr (io::Error)}

/// Runs the future `f` on the shared `CORE` until it finishes or the timeout occurs.
///
/// * `duration` - Primes the timeout.
/// * `f` - The future which response time needs to be limited.
pub fn due<F, R, E> (duration: Duration, f: F) -> Receiver<DueResult<R, E>>
where F: Future<Item=R, Error=E> + Send + 'static, R: Send + 'static, E: Send + 'static {
  let (sx, rx) = oneshot::channel();
  CORE.spawn (move |handle| {
    let timeout = Timeout::new (duration, handle) .expect ("!Timeout");
    let timeout = timeout.map (|_| DueResult::Timeout) .map_err (|e| DueResult::TimeoutErr (e));
    let select = f.map (|r| DueResult::Ok (r)) .map_err (|e| DueResult::Err (e)) .select (timeout);
    select.then (move |sr: Result<(DueResult<R, E>, _), (DueResult<R, E>, _)>| -> Result<(),()> {
      let _ = sx.send (match sr {Ok ((due, _)) => due, Err ((due, _)) => due});
      Ok(())})});
  rx}

lazy_static! {
  /// Shared asynchronous reactor.
  pub static ref CORE: tokio_core::reactor::Remote = start_core_thread();}
```
