### ISSUE TITLE
Infinite loop on FramedRead

### ISSUE THREAD

**Issue by colindjk** [tokio-rs/tokio-core#112]
Currently I am trying to make a messaging application similar to the chat example given for tokio-core, it can be located [here](https://github.com/colindjk/tin_can_telephone).

I made what I thought was a fairly good attempt at reading in messages following a particular structure and then sending them to the appropriate clients.

I implemented the "Codec" trait for a nice DataParser object, and pass that object into a Framed struct like so:

```rust
    let server = socket.incoming().for_each(|(stream, addr)| {
                                                                            
        println!("Connected to client {}", addr);
                                                                            
        let mut server_sender = sender.clone();
                                                                            
        // reader   -> sender
        // receiver -> writer
        let (reader, mut writer) = TctClient::new(stream, addr)
            .framed(DataParser).split();
        let (sender, receiver) = mpsc::unbounded();
                                                                            
        clients.borrow_mut().insert(addr.port(), sender);
                                                                            
        let clients_inner = clients.clone();
                                                                            
        // Every message received over the stream, from client
        let reader = reader.for_each(move |msg: Data| {
            println!("Reading message {}", msg.id().unwrap());
            // let clients = clients_inner.clone()?
            if let Some(id) = msg.id() {
                println!("Sending message {}", msg.id().unwrap());
                clients_inner.borrow_mut().get_mut(&id)
                    .unwrap_or(&mut server_sender)
                    .send(msg)
                    .or_else(
                        |err| Err(IoError::new(ErrorKind::Other, err)))
                //Ok(())
            } else {
                panic!("Client reported error")
            }
        }).map_err(|_| ());
                                                                            
        let receiver = receiver.for_each(move |mut msg| {
            println!("Writing message");
            match writer.start_send(msg) { // handle it like 'send'
                Ok(AsyncSink::Ready) => Ok(()),
                Ok(AsyncSink::NotReady(balls)) => panic!("failed to send"),
                Err(err) => Err(())
            }
        });
                                                                            
        //let clients = self.clients.clone();
        //let connection = receiver.map(|_| ()).select(reader.map(|_| ()));
        handle.spawn(receiver);
        handle.spawn(reader);
                                                                            
        Ok(())
    });
```

The problem arises when I make a read from a client with an id which exists on the HashMap of clients, and not in any other case.

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have a self-contained example (ideally with a `Cargo.lock`) that we could use to reproduce the behavior?

**Comment by colindjk** [comment]
Well I feel silly, I fixed the original issue, but came accross a second! First of all, I should be emptying out the buffer apparently XD. In my encode function I now have this 

```rust
fn decode(&mut self, buf: &mut EasyBuf)
    -> Result<Option<Self::In>, IoError>
{
    let len = buf.len();
    if let Ok(val) = from_slice(buf.as_ref()) {
        buf.drain_to(len);
        Ok(Some(val))
    } else {
        Err(IoError::new(ErrorKind::Other, "Decode error".to_string()))
    }
}
```
When I made the original issue post I did not have "buf.drain_to(len)", which allows me to clear the buffer, as opposed to the situation I had before where I read the same buffer half a billion times (whoopsie). 

However! Now I have a new and related issue, in my messaging application, I can only send one message per connection. I send my first message, it reaches the sendee, and all is well. However, if I try to send more than one message, (OR I give some garbage bytes before my JSON message), then nothing gets sent. 

In fact, no attempt is made even to _decode_ the message that I try to send, meaning I don't even have a chance to read it from my socket reader.

Somehow, there is logic in tokio (which I'm checking out as we speak) which allows me to make one frame, and then after that no frames! So yeah... I'll try to debug it myself; but you can clone my git repo right [hur](https://github.com/colindjk/tin_can_telephone).

In order to test it, I currently just use telnet and connect via "telnet localhost 8080" in a terminal. An example message like so -
"Message"{"id":"port_number_here","msg":"hello world"}

I will be updating it often so use [this specific commit](https://github.com/colindjk/tin_can_telephone/commit/f5000efdedaf8a8066994aff668164d042212253) to test what I'm talkin' about. It might be an issue with what I'm doing, but either way, a good journey into learning the tokio magic. 

Thanks for the response!
