### ISSUE TITLE
Failed to empty EasyBuf after 'decode'

### ISSUE THREAD

**Issue by colindjk** [tokio-rs/tokio-core#113]
So I just copied this comment over from another issue, as I believe this may be an actual issue with the tokio library. 

```rust
fn decode(&mut self, buf: &mut EasyBuf)
    -> Result<Option<Self::In>, IoError>
{
    let len = buf.len();
    if let Ok(val) = from_slice(buf.as_ref()) {
        buf.drain_to(len);
        Ok(Some(val))
    } else {
        Err(IoError::new(ErrorKind::Other, "Decode error".to_string()))
    }
}
```
When I made the original issue post I did not have "buf.drain_to(len)", which allows me to clear the buffer, as opposed to the situation I had before where I read the same buffer half a billion times (whoopsie). 

However! Now I have a new and related issue, in my messaging application, I can only send one message per connection. I send my first message, it reaches the sendee, and all is well. However, if I try to send more than one message, (OR I give some garbage bytes before my JSON message), then nothing gets sent. 

In fact, no attempt is made even to _decode_ the message that I try to send, meaning I don't even have a chance to read it from my socket reader.

Somehow, there is logic in tokio (which I'm checking out as we speak) which allows me to make one frame, and then after that no frames! So yeah... I'll try to debug it myself; but you can clone my git repo right [hur](https://github.com/colindjk/tin_can_telephone).

In order to test it, I currently just use telnet and connect via "telnet localhost 8080" in a terminal. An example message like so -
"Message"{"id":"port_number_here","msg":"hello world"}

I will be updating it often so use [this specific commit](https://github.com/colindjk/tin_can_telephone/commit/f5000efdedaf8a8066994aff668164d042212253) to test what I'm talkin' about. It might be an issue with what I'm doing, but either way, a good journey into learning the tokio magic.

**Comment by rrichardson** [comment]
The symptoms you describe leads my first guess is that you don't have more room to read from the socket into the EasyBuf after that drain_to.   

When reading in to the buffer, EasyBuf::get_mut will provide a buffer between 0 and `start` in which to write.  `start` is set to the len provided into `drain_to`,  where the end is the previous end.

Nothing is immediately apparent,  but I'd recommend tracing the len(), start and end of the easyBuf as you're debugging.

**Comment by colindjk** [comment]
So I started using delimiters like the in line example, that way I could parse together messages more easily. 

This somehow fixed the issue, even though I actually checked the len vs delimiter index and they are the same.... welp. 

For now I'm closing this as the bug disappeared, thanks for the help!
