### ISSUE TITLE
HUP handling for pipes missing

### ISSUE THREAD

**Issue by rotty** [tokio-rs/tokio-core#117]
When using tokio-core with POSIX pipes, pending readers should be, but are not, notified when a `mio::Ready::hup()` event happens. This event is produced when the other (i.e. write) end of the pipe is closed, and can be treated like an edge-triggered read event.  I think a similiar issue should occur with TCP streams and `shutdown()`, which also causes `hup` events.

When (under Linux) `epoll_wait()` returns `EPOLLHUP` without `EPOLLIN`, a successive `read()` will indicate EOF without blocking. Otherwise, when `EPOLLHUP` is set in combination `EPOLLIN`, the current code already handled it correctly, assumming that `read()` is attempted until `EAGAIN`/`EWOULDBLOCK` is encountered (i.e. consuming all data available without blocking).

Since the behavior when `EPOLLHUP` was indicated in combination with `EPOLLIN` was already correct, exposing this issue requires ensuring that the consumer has emptied the pipe's internal OS buffers before closing the other end.

I'll submit a PR attempting to fix this shortly.

**Comment by alexcrichton** [comment]
Oh yeah if EPOLLHUP implies read readiness, we should definitely handle it!
A PR would be most welcome!

Just let me know if you need any help
