### ISSUE TITLE
Consider having tokio-core be only for traits and move the reactor (dependencies) -> tokio-io

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#119]
This is a placeholder issue for the discussion.

**Comment by aajtodd** [comment]
It's already a bit difficult to keep track of everything IMHO, which is not necessarily a reason not to but I also am not seeing a benefit in such a move. 

Care to elaborate what the perceived benefits you see are? A trait only crate seems odd, is their precedence elsewhere (other than tokio-service)?

**Comment by dwrensha** [comment]
It seems like a separate `tokio-io` crate would be a natural place to define the `AsyncRead` and `AsyncWrite` traits discussed in #61.

**Comment by aajtodd** [comment]
Ahh OK, that seems reasonable.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
