### ISSUE TITLE
Implement more traits for EasyBuf

### ISSUE THREAD

**Issue by Yamakaky** [tokio-rs/tokio-core#120]
`Clone`, `Deref`, `Into<Vec<u8>>` would be a start.

**Comment by tailhook** [comment]
I think also `Index<..>` would be cool. Because `drain_to` is very-limited.

**Comment by Yamakaky** [comment]
`Deref<[u8]>` would be sufficient, I think?

**Comment by tailhook** [comment]
No, I mean slicing should return `EasyBuf` not `&[u8]`, because `EasyBuf` has a static lifetime, so can be a part of a return value of the protocol parser (and `EasyBuf` is specifically designed not to make a clone of the underlying data for that, it's how `drait_to` works)

**Comment by Yamakaky** [comment]
Oh, yeah

**Comment by alexcrichton** [comment]
The intention was to be *very* conservative for the initial iteration that we could tack on more functionality later, but I couldn't mind adding a few more common trait impls and such. I'd prefer to avoid `Deref` for now to avoid conflicts with the slice API, but other common traits should be good to go.

**Comment by aturon** [comment]
cc https://github.com/tokio-rs/tokio-core/pull/128

**Comment by manuel-woelker** [comment]
@tailhook I was looking at implementing Index for EasyBuf, with Output = EasyBuf. But it seems `index`
returns `&Self::output`. That means my naive approach - creating a new EasyBuf instance to return - won't work since it does not live long enough. Any pointers on how to proceed? Would this require `IndexGet`/`IndexMove`?

**Comment by tailhook** [comment]
@manuel-woelker, hm, looks like we can't do that :(. The best way I can see is to have a method `x.slice(a..b)`.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
