### ISSUE TITLE
Benchmark of the echo server

### ISSUE THREAD

**Issue by haraldh** [tokio-rs/tokio-core#122]
```
Benchmarking: 127.0.0.1:12345
1000 clients, running 26 bytes, 60 sec.

Speed: 155607 request/sec, 155607 response/sec
Requests: 9336428
Responses: 9336427
```

Very poor against https://github.com/haraldh/rust_echo_server

See the README.md for more results.

**Comment by tailhook** [comment]
Sure, as far as I can see you're comparing 1 thread echo server with 1000 thread echo server (your echo server creates a thread per connection, right?)

**Comment by haraldh** [comment]
True. Sorry, was mislead by the name of "spawn" in the tokio crate. Thought tokio would do the same in the background.

**Comment by alexcrichton** [comment]
Yes I think this is just related to the fact that the sample echo server is single-threaded, only accepting connections on one core. I [adapted it to work on multiple threads](https://gist.github.com/7174bbf6c2359f2b9a2de0d0d3973a09) and got the following numbers:

Against the [code in `rust_echo_server`](https://github.com/haraldh/rust_echo_server/tree/e352d54eca46ad1bc25f78e4d4be01454c36ba73):

```
Benchmarking: 127.0.0.1:12345
1000 clients, running 26 bytes, 60 sec.

Speed: 462805 request/sec, 462805 response/sec
Requests: 27768349
Responses: 27768346
```

Against the multithreaded tokio-core benchmark:

```
Benchmarking: 127.0.0.1:8080
1000 clients, running 26 bytes, 60 sec.

Speed: 678832 request/sec, 678832 response/sec
Requests: 40729974
Responses: 40729971
```

In light of that I'm going to close this issue, but if you feel like we need any changes just let me know!

**Comment by haraldh** [comment]
Nice! Seems like the CPU cache1/2 size makes rust_echo_server perform better on my machine:

multithreaded tokio-core:
```
Speed: 636702 request/sec, 636700 response/sec
```

rust_echo_server:
```
Speed: 697627 request/sec, 697627 response/sec
```

Anyway, your gist should be part of the tokio examples as a starting point for others.

**Comment by alexcrichton** [comment]
Interesting! 

In any case I've avoided examples like that in tokio for now as I'm not sure that it's really the best way to add multi thread support to a server. It's Unix specific and has ramifications on the rest of the system. I'd prefer to figure out a better method of multithreading a Unix server with mio, but it's still a work in progress!

**Comment by dyxushuai** [comment]
The count of `Core` instance is same as the threads count that means we have the same number of `epoll` ?  Will this affects the performance of server ?
