### ISSUE TITLE
Avoid unnecessary memory initialization for tokio_core::io::read

### ISSUE THREAD

**Issue by kkimdev** [tokio-rs/tokio-core#123]
Currently, users have to pass initialized buffer (unless using `unsafe`) unnecessarily.
```rust
let buffer = vec![0u8; 1024];
tokio_core::io::read(reader, buffer)
```

How about having a read method that avoids the unnecessary initialization?
```rust
let buffer = Vec::with_capacity(1024);
tokio_core::io::read2(reader, buffer)
```

`read2` will use Vec::set_len internally, possibly up to the vector's capacity.

**Comment by tanriol** [comment]
Note: the [buffer](https://docs.rs/crate/buffer/) crate seems to implement that for `Read`. Maybe it makes sense to use it?

**Comment by carllerche** [comment]
The plan is to work to integrate bytes: http://github.com/carllerche/bytes. I would have to look at the `buffer` crate, however it has been fairly tricky to introduce uninitialized writes w/o exposing uninitialized memory to safe code.

**Comment by kkimdev** [comment]
It looks like [buffer](https://docs.rs/crate/buffer/) is almost exactly what I described, but implemented as a seperate trait.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
