### ISSUE TITLE
reactor::Core::new() always allocates ~20MB

### ISSUE THREAD

**Issue by dwrensha** [tokio-rs/tokio-core#124]
Currently the initial slab capacity is [hardcoded to 64K](https://github.com/tokio-rs/tokio-core/blob/f036691681ae7868fc60480f99b9f2b62f1a63eb/src/reactor/mod.rs#L38). This causes a new `reactor::Core` to consume upwards of 20MB of heap memory, even if the program only ever uses it to serve a small number of connections.

It should be possible to specify the desired starting capacity of a `Core` upon construction.

**Comment by frewsxcv** [comment]
Is there any value in also having a `Core::capacity` method to return what that value is? This is done in `std`:

* https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity
* https://doc.rust-lang.org/std/vec/struct.Vec.html#method.capacity

**Comment by dwrensha** [comment]
I've updated the title of this issue in light of [this comment](https://github.com/tokio-rs/tokio-core/pull/125#issuecomment-267650777). The real problem that I care about is that `Core::new()` unavoidably does a lot of allocation. Whether or not the amount of allocation should be configurable is a separate question.
