### ISSUE TITLE
question:when to call `poll` method ?

### ISSUE THREAD

**Issue by imiskolee** [tokio-rs/tokio-core#129]
in `future` trait,we know its required method to control IO state.but,i donnt know when to call `poll`.

**Comment by bluejekyll** [comment]
I'll try and answer. Generally, you don't need to call poll. This is called by some other processor, like the `tokio_core::reactor::Core` after the future has been registered there during it's `run()` or `turn()` functions. The only case you'd need to call `poll()` is if you are wrapping another future and want to call that futures `poll()` function to track some kind of internal state.

**Comment by alexcrichton** [comment]
@bluejekyll is spot on, although feel free to let me know if that doesn't answer the question at hand!
