### ISSUE TITLE
UdpFramed splits each udp packet by every 1024 bytes

### ISSUE THREAD

**Issue by wayslog** [tokio-rs/tokio-core#130]
environments: macOS 10.12.1
rustc: rustc 1.15.0-nightly (0bd2ce62b 2016-11-19)

When I use tokio in my project, in [there](https://github.com/wayslog/lingo-proxy/blob/master/src/lib.rs#L127). I want receive the whole packet when each Framed stream's `poll` is called. But, somehow the UpdCodec split each packet into parts which was 1024 bytes.
So, I get a wrong result of parsing  the whole packet.

And, when I change my test data to 1024 bytes , it works well.

**Comment by alexcrichton** [comment]
Thanks for the report! Taking a look again at `src/udp/frame.rs` I can't see any point where this obviously comes from unfortunately. Do you have a way to reproduce that I could play around with locally?

**Comment by wayslog** [comment]
Oh, my fault.

I test my program by using command `netcat` (`nc`) . But this command, in macOS, will suddenly split packet if that packet is larger than 1024 bytes. So that I get two or more udp packets in fact. 

So `tokio-core` has nothing to do with the matter, but I think you can still record it for the same issues.
