### ISSUE TITLE
Update TcpStream::new() and TcpStream::connect() to not use Box allocations

### ISSUE THREAD

**Issue by alreece45** [tokio-rs/tokio-core#133]
`TcpStream::new()` and `TcpStream::connect_stream()` use IoFuture-- which is a `Box`. They should probably be updated to return concrete types. 

Discussion on gitter suggests IoFuture may be removed in the future. https://github.com/alexcrichton/futures-rs/issues/228 suggests that `Futures::boxed()` may be removed as well.

This will probably be something for 0.2.0

**Comment by alexcrichton** [comment]
This has been done!
