### ISSUE TITLE
file io using tokio event loop

### ISSUE THREAD

**Issue by florianjacob** [tokio-rs/tokio-core#138]
I'm trying to build a http server for static files using the tokio version of hyper, but I could not find anything like a FileStream to chain with a TcpStream, or any hints on how to asynchronously read a file with tokio instead of premade strings like `tokio_core::io::write_all(socket, "Hello World".as_bytes())`.

Is that actually possible somehow, or is the only option to implement a FileStream by myself which uses `std::thread::spawn` to get a thread per stream which then uses the blocking `std::fs::read`, or something like this?

**Comment by tailhook** [comment]
Yes, basically you can't have any sane asynchronous filesystem IO in linux (so no such API in tokio). You need to use threads.

You may want to take a look at [tk-sendfile](https://github.com/tailhook/tk-sendfile) which works only on linux yet. But also serves as an example of how to combine file io in CpuPool and tokio-core loop for handling network.

**Comment by alexcrichton** [comment]
Ah yeah you'll likely want to move any operations that use filesystem APIs into a thread pool because unfortunately Unix doesn't handle them very well asynchronously. We could add APIs for Windows, perhaps, but it still wouldn't address the cross-platform async filesystem bindings.

**Comment by florianjacob** [comment]
Thanks to both of you for the explanation what's going on there. 😄  Also, tk-sendfile seems to be exactly what I need. 👍
