### ISSUE TITLE
Race when reading messages using Sender + Receiver pair

### ISSUE THREAD

**Issue by svyatonik** [tokio-rs/tokio-core#143]
We are using mio + tokio-core + futures + futures-cpupool to implement some network protocol (basically - sending and responding to messages).
To read incoming messages, we use simple future, based on tokio_core::io::read_exact - first we read message header, then - message payload.
We spawn this future on CpuPool && on event loop (tokio_core::reactor::Core). After reading header + payload is completed => future is spawned again.
This works for some time, but eventually our futures stop spawning on event loop => no messages are read from network.
I've invested some time trying to understand - what's going on there && here are my thoughts:
1) we are spawning our future on event loop using tokio_core::reactor::Remote handle
2) Remote::spawn function sends message to the 'event loop thread' using tokio_core::reactor::channel::Sender:
https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L578
https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/channel.rs#L47
3) sender uses custom lock-free Queue to store messages:
https://github.com/tokio-rs/tokio-core/blob/master/src/mpsc_queue.rs
and pair of mio::channel::{SenderCtl, ReceiverCtl} for signalling that queue is not-empty:
https://github.com/carllerche/mio/blob/master/src/channel.rs
4) when message is sent, it is pushed to the queue, and then SenderCtl::inc is called:
https://github.com/carllerche/mio/blob/master/src/channel.rs#L196
inc method first checks if number of pending messages is 0 && then calls set_readingess(Ready) to awake the Poll.
**This is important, because when second message is sent via the same Sender/Receiver pair, readiness is not set again**.
5) when Poll receives notification that message is ready, control is transferred back to tokio_core::reactor::Core:
https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L282
and it starts processing incoming messages queue:
https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L385
6) **here's second important part - Receiver::recv method**:
https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/channel.rs#L55
here you can see that in case when Queue::pop returns **PopResult::Inconsistent**, recv returns None && no messages are processed (Core::consume_queue stops processing messages).
Please bear in mind that mio::ReceiverCtl::dec is called only when item is 'popped' out of Queue:
https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/channel.rs#L62
So if queue was in inconsistent state during pop, then SenderCtl.inner.pending is not decreased => next time message is sent using Sender::send, message won't be read, because receiver is notified only when first message is sent (see (4) above).

What has fixed this issue for our project is removal of 'if 0 == cnt' condition here:
https://github.com/carllerche/mio/blob/master/src/channel.rs#L198
So that readiness flag is set even when message is not the first one in the queue. But:
1) as I understand this can lead to spurious wakeups of Poll (because the whole queue can be read on previous wakeup)
2) the problem is not with the SenderCtl+ReceiverCtl pair itself, but with ther usage along with lock-free Queue in tokio-core
So maybe this should be fixed in some other way, but if you think this fix is OK - I can try to create PR in mio repository.

**Comment by alexcrichton** [comment]
Thanks for the detailed report @svyatonik! Out of curiosity, do you have a reproduction for this failure? (sporadically failing is fine). I'd love to check in a unit test and explore this further.

I haven't heavily scrutinized the ctl bits from mio yet but this reminds me that I've been intending to rip out `reactor::channel` in favor of the channels in the `futures` crate itself. I did that in https://github.com/alexcrichton/tokio-core/commit/2caad85d44c7a52bf470018ea98fe8b61c13059c, and could you test that out to see if it fixes your problems?

**Comment by svyatonik** [comment]
@alexcrichton Not yet, unfortunately - will try to make a small test for this a bit later && check your branch.

**Comment by svyatonik** [comment]
Repository with small utility which you can use as a basis for unit test:
https://github.com/svyatonik/tokio_core_race
I've also changed mio && tokio-core source a bit, just to illustrate what's going when meeting the race, but haven't committed my changes - these are described in readme.md

**Comment by svyatonik** [comment]
About testing with your branch - I have a problems with compiling our project after switching to your code:
```
    |      ^^^^^^^^ the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<futures::sync::mpsc::UnboundedSender<tokio_core::reactor::Message>>`
    |
    = note: `std::cell::RefCell<futures::sync::mpsc::UnboundedSender<tokio_core::reactor::Message>>` cannot be shared between threads safely
    = note: required because it appears within the type `tokio_core::reactor::Remote`
```
So maybe this should be fixed in your branch somehow (as I understand, Remote is now not Sync)? Or should we change our code to make Remote usable again?

**Comment by alexcrichton** [comment]
Oh yeah that's a property of `Remote` which I lost on that temporary branch, and we definitely want to keep `Remote` as `Sync`. I'll work on updating that.

**Comment by alexcrichton** [comment]
@svyatonik ok want to test out this commit? https://github.com/alexcrichton/tokio-core/commit/5979a6d59d5a20b7517a6c7b96a87eee9ce0696b

**Comment by svyatonik** [comment]
@alexcrichton tested this commit. And I have two news:
1) positive - **looks like** race issue is fixed;
2) not-so-positive - mio poll now returns instantly here:
https://github.com/alexcrichton/tokio-core/commit/5979a6d59d5a20b7517a6c7b96a87eee9ce0696b#diff-245f7d251f7503191c63a5d19b4aae18R263
When starting with `RUST_LOG=trace`, I can see that when app is running, poll returns ~20000-22000 times per second, thus consuming the whole single CPU. So app is working very slow && I can't be 100% sure that race is gone (but I suppose so, as previously it was because this thread was sleeping when it shouldn't && now it never sleeps). Some stats:
```
svyatonik@xwnotebook:~/dev/myapp.test/myapp$ grep -rn "loop time - Instant { tv_sec: 238513" start_trace.log | wc -l
20266
svyatonik@xwnotebook:~/dev/myapp.test/myapp$ grep -rn "loop time - Instant { tv_sec: 238512" start_trace.log | wc -l
21870
```
During most of wakeups, **this queue is empty** (checked with trace in Async::Ready branch):
https://github.com/alexcrichton/tokio-core/commit/5979a6d59d5a20b7517a6c7b96a87eee9ce0696b#diff-245f7d251f7503191c63a5d19b4aae18R391
So I think that maybe `rx_readiness` is never reset? However, I do not know in details, how mpsc channel from futures-rs works, but it looks so that it constantly Ready(Read).

**Comment by alexcrichton** [comment]
Oops, indeed! How about https://github.com/alexcrichton/tokio-core/commit/5979a6d59d5a20b7517a6c7b96a87eee9ce0696b?

**Comment by alexcrichton** [comment]
Er, I mean https://github.com/alexcrichton/tokio-core/commit/ed9037a73c10fb3521d1b0599e13994de5eb8fb0

**Comment by svyatonik** [comment]
@alexcrichton checked - looks like it works now :1st_place_medal: Thank you very much! :)

**Comment by alexcrichton** [comment]
Awesome, thanks for testing @svyatonik!
