### ISSUE TITLE
Consider making Codec error an associated type

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/tokio-core#146]
It doesn't make much sense that every `Codec`'s `decode` method returns `io::Result`, given that the vast majority of `Codec`s shouldn't be performing any IO at all, but might instead return application-specific encoding/decoding errors.

**Comment by aturon** [comment]
The use of `io::Result` here is related to the fact that codecs are used in the transport layer of protocols, which currently operates entirely in terms of I/O errors; it is, after all, the I/O layer. It's possible to embed custom errors into I/O errors.

Part of the impetus for sticking with I/O errors, also, is the fact that tokio-proto requires the transport layer to generate I/O errors. I think we should make a change here only if we also change tokio-proto. It's not clear to me offhand how painful such a change would be in practice.

@Ralith, if you felt like exploring a PR against tokio-proto generalizing the transport error type, just so we could gauge the fallout, that's be helpful!

**Comment by Ralith** [comment]
> The use of io::Result here is related to the fact that codecs are used in the transport layer of protocols, which currently operates entirely in terms of I/O errors; it is, after all, the I/O layer.

Be that as it may, the responsibilities of Codec in and of itself have nothing to do with I/O per se at all. As far as I can tell, most reasonable implementations will never produce a real I/O error, although some may instead produce some sort of higher-level decoding error. My current uses of Codec can't even produce any errors at all, but this API forces me to place misleading unwrap calls wherever they're used.

> It's possible to embed custom errors into I/O errors.

If the intention is to have the user package an arbitrary error value in a heap-allocated trait object, rather than to expose genuine system-produced errors, why not represent that accurately by using `Box<Error + Send + Sync>` or something instead? IMO encouraging people to stuff everything into a single universal type like this is severely unidiomatic, but if that's what the design calls for, it would be much clearer to be up front about it.

> Part of the impetus for sticking with I/O errors, also, is the fact that tokio-proto requires the transport layer to generate I/O errors. I think we should make a change here only if we also change tokio-proto. It's not clear to me offhand how painful such a change would be in practice.

If `Codec` is intended to serve the needs of tokio-proto over the needs of tokio-core users in general, wouldn't it be better for it to be part of that library instead of tokio-core, with tokio-core instead having a more general helper? That might be a good opportunity to unbundle encoding and decoding, too.

> @Ralith, if you felt like exploring a PR against tokio-proto generalizing the transport error type, just so we could gauge the fallout, that's be helpful!

I've never used tokio-proto. I might take a look if I get the time (I expect it's just a matter of introducing `enum TransportError<T> { Io(io::Error), Transport(T) }`), but mainly I'm concerned about tokio-core's API suffering for the sake of a downstream library that may not even be in use in any given tokio-core using project.

**Comment by Kixunil** [comment]
I agree with @Ralith. The error type should be associated. I need to pass my own errors and don't want to put them behind `Box<Error + Whatever>`.

Edit: unbundling decoding and encoding: please, yes! The current situation doesn't allow using Unix pipes.

**Comment by tikue** [comment]
As another data point, I perform serialization/deserialization with bincode in the codec, and right now I propagate deserialization errors by doing `type In = Result<Decode, bincode::Error>;`, which seems hacky. It also feels hacky to return `io::Error::new(io::ErrorKind::Other, serialize_error)` when serialization fails.

**Comment by alexcrichton** [comment]
Done upstream in tokio-io: https://github.com/tokio-rs/tokio-io/issues/12
