### ISSUE TITLE
`Framed` should terminate reading when always ready

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#153]
@mdevlamynck [reported](https://github.com/tokio-rs/tokio-core/issues/38#issuecomment-274330942):

While playing with the echo server example, I've noticed that if you feed the server with something like ```cat /dev/urandom | nc 127.0.0.1 12345``` it just buffers the input until EOF (which can quite quickly fill up Gbs of ram) never calling the decode method of Codec before the EOF.

I think this is caused by the use of read_to_end in Framed : https://github.com/tokio-rs/tokio-core/blob/master/src/io/frame.rs#L305.

**Comment by carllerche** [comment]
Because it increases the tokio API surface. In general, I prefer smaller functions that can be combined than adding speciality traits, etc..

Given that there already is a *nix specific FromRawFd and none of the other libraries (mio, std, etc...) use a Tcp extension trait to convert from a Raw FD, it seems like it would go against the grain.

**Comment by mdevlamynck** [comment]
You have a read and read_exact, so we could read a max of X bytes at a time and let the codec decide if we need to continue reading or if what we already read is enough.

The tricky part is how to decide how many bytes to read at a time. I feel like the codec should be in charge of this. But I understand your concern for API surface. I'm not sure what would be the right solution.

**Comment by alexcrichton** [comment]
Yeah currently `read_to_end` is nice so if the underlying socket is a `TcpStream` then it won't zero out memory before doing the read, but other than that we should just switch to `read` in general for this operation.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
