### ISSUE TITLE
Consider removing the argument to `Loop::run`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#16]
The argument passed to `Loop::run` adds an extra step to getting an event loop running. I also am not convinced that it provides the easiest way to manage shutting down a loop.

One question that needs to be asked when shutting down an event loop is what should happen with open sockets? There will still be the ability to have socket handles around but they won't be functional anymore since the event loop will go away.

One reason why I think getting rid of the argument to `Loop::run` is that there are going to be two primary shutdown cases:

1) Do nothing... run the event loop forever and have the process shutdown handle cleaning up.

2) Do a proper shutdown, the steps will be something like:
- Wait for a shutdown event (ctrl-c, or something else)
- Stop accepting new sockets
- send a shutdown signal to all open sockets
- Wait a grace period to allow open sockets to correctly shutdown
- Hard shutdown any lingering connections
- Shutdown the loop

Also, for the event loop proper, there are multiple shutdown steps that aren't necessarily well represented by taking a future:
- Stop accepting new tasks (spawn fails) and shutdown _after_ all existing sources close
- Stop accepting new tasks and shut the loop down immediately

This could be handled by adding functions on `LoopHandle`:

``` rust
fn shutdown(&self) -> Shutdown;

fn shutdown_now(&self) -> Shutdown;
```

where `Shutdown` is a future that resolves when the loop is successfully shutdown.

**Comment by alexcrichton** [comment]
On crucial feature of `run` is that it allows executing a non-`'static` future, and is currently the only method of doing so for I/O futures. The `wait` function is the other escape hatch for that, but `run` was intended as the equivalent which runs the event loop while you're waiting.

I agree though that we should have a way to have "graceful shutdown" where it waits for all tasks on the event loop to finish executing before returning. Along those lines perhaps we could have two functions here? Naming may be difficult, but it seems like we may want two pieces of functionality.

**Comment by carllerche** [comment]
Makes sense. I like the idea of two functions.

**Comment by alexcrichton** [comment]
Some discussion in IRC today:
- It seems reasonable to expose a `Shutdown` future which resolves when there are no more tasks spawned on an event loop
- This would mean that there's no need for a separate function
- Right now `run` is useful for a no-lifetime-bound future, but it's questionable how useful this is if `Core` gets a type parameter
- We may be able to punt on this to 0.2. Any new form of "graceful shutdown" could perhaps be accompanied with a deprecation of `run` if necessary.

**Comment by alexcrichton** [comment]
0.1 has shipped with this API, so I'm going to close in favor of https://github.com/tokio-rs/tokio-core/issues/33 for graceful shutdown.
