### ISSUE TITLE
How to avoid starvation? Or how to “yield” the current future?

### ISSUE THREAD

**Issue by blckngm** [tokio-rs/tokio-core#165]
I wrote a simple IP tunnel ([TiTun](https://github.com/sopium/titun)) that uses tokio-core. For the most part it works well. But there is a problem worth telling: starvation.

I have in my code `Future`s that are implemented like this (it's in `src/titun.rs`):

```rust
struct Common {
    crypto: Crypto,
    sock: UdpSocket,
    tun: PollEvented<Tun>,
    buf: Vec<u8>,
}

struct SockToTun {
    common: Rc<RefCell<Common>>,
    remote_addr: Option<Rc<RefCell<Option<SocketAddr>>>>,
    buf_to_write: Option<Vec<u8>>,
}

// poll and try_nb! are somewhat like async/await...only the function continues from the start,
// not where it was interrupted.
//
// much easier to write than closures.

impl Future for SockToTun {
    type Item = ();
    type Error = TiTunError;

    fn poll(&mut self) -> Poll<(), TiTunError> {
        let mut common = self.common.borrow_mut();
        // Explicit deref_mut to get mutable references to disjoint fields.
        let mut common = common.deref_mut();
        loop {
            self.buf_to_write = if let Some(ref b) = self.buf_to_write {
                try_nb!(common.tun.write(b.as_slice()));
                None
            } else {
                None
            };

            let (l, addr) = try_nb!(common.sock.recv_from(common.buf.as_mut()));
            if let Some(p) = common.crypto.decrypt(common.buf[..l].as_ref()) {
                if let Some(ref r) = self.remote_addr {
                    let mut rr = r.borrow_mut();
                    if *rr != Some(addr) {
                        *rr = Some(addr);
                        info!("Peer address set to {}", addr);
                    }
                }
                self.buf_to_write = Some(p);
            } else {
                debug!("decryption failed");
            }
        }
    }
}
```

It is inspired by, and similar to, the `echo-udp` example, and `io::copy::Copy`.

But the `loop` may loop forever or for a very long period of time, if `read` or `send_to` do not block. In that case, other futures and tasks won't have a chance to run at all or for a very long period of time.

So, I'd like to ask, how to avoid this starvation problem? Or how to tell the event loop: “I am not finished, but give others some time”, i.e. how to implement “yield”?

Perhaps such a mechanism should be added to tokio-core? (Or futures? I'm not sure.)

**Comment by alexcrichton** [comment]
Ah yeah so currently we don't have a first-class abstraction for this, but right now the best way to "yield" is to:

```rust
task::park().unpark();
return Ok(Async::NotReady)
```

That means you'll just be scheduled on the next turn of the loop

**Comment by blckngm** [comment]
Alright. Thanks!

Please consider add an abstraction for this. And please consider incorporating this into constructs that use a naive loop, e.g. `Forward`, `Copy`, etc.

Otherwise feel free to close this issue.

**Comment by blckngm** [comment]
Didn't noticed that there are already quite a few related issues on futues:

* alexcrichton/futures-rs#177
* alexcrichton/futures-rs#352
* alexcrichton/futures-rs#353
* alexcrichton/futures-rs#354

Closing.
