### ISSUE TITLE
tokio_core::io::Framed should implement Debug

### ISSUE THREAD

**Issue by sunshowers** [tokio-rs/tokio-core#171]
Without that, the following code (that I have in a test) doesn't work:

```rs
framed.into_future().wait().unwrap()
```

That's because the error type is actually `(Framed::Error, Framed)`, and `unwrap()` requires that the error type implement `Debug`.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by manuel-woelker** [comment]
What would a `Debug` implementation look like?
 * derived
 * or custom, but only if `upstream` and `codec` implement `Debug`
 * or custom, independent of `upstream` and `codec` Debug impls
 * Show `eof`/`is_readable` flags?
 * Show content or length of `rd`/`wr` buffers?

**Comment by alexcrichton** [comment]
Oh I'm fine with whatever's readable/easy to implement. We probably don't want to show the full contents of the buffers (as that may be a lot), but other than that we should just be sure to restrict type parameters to also implement `Debug` in case we want to throw those in in the future.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
