### ISSUE TITLE
Having both "sync" and "sink" in the API makes verbal discussion v. confusing

### ISSUE THREAD

**Issue by jsgf** [tokio-rs/tokio-core#176]
The other day I had a conversation in which we were a few mins in before we realized we were talking at cross purposes because of a sync/sink confusion.

Maybe rename `futures::sync`? Or "sink" -> "drain" (or something)?

**Comment by carllerche** [comment]
Thanks for the report. I would suggest opening this in the `futures` issue tracker as both `sync` and `sink` terminology come from there :)

Cheers.

**Comment by jsgf** [comment]
Crap, wrong window :/
