### ISSUE TITLE
terrible performance when using CpuPool for response stream

### ISSUE THREAD

**Issue by scottlamb** [tokio-rs/tokio-core#177]
I'm using mio/futures/futures-cpupool/tokio-core/tokio-proto/hyper for a test program which serves files from local disk. It gets terrible performance. I don't fully understand the problem or what layer(s) is/are responsible, but this seemed like a decent place to try to figure it out.

Since the tokio reactor is single-threaded, it makes sense to do blocking disk I/O on a separate thread pool so that other requests won't get stuck. My test program does this (even though in this trivial example the reactor has no other useful work to do). It's really, really slow (> 10ms to serve a single-byte file that's already in the OS page cache). When I do everything directly from the reactor thread, latency is fine (hundreds of microseconds).

In particular, the slowdown seems to be caused by having the body stream be produced on the `CpuPool` and sent over a `futures::sync::mpsc::channel`.

Running my example:

```
$ git clone https://github.com/scottlamb/http-entity
$ cd http-entity
$ git checkout 691aa66  # current tip of hyper-0.11.x branch
$ echo > f
$ cargo run --release --example serve_file -- f
```

and benchmarking in four configurations:

   * /inline-inline uses the reactor to open/fstat the file and to stream chunks
   * /pool-inline uses the CpuPool for open/fstat, reactor to stream chunks
   * /inline-pool
   * /pool-pool

```
$ for i in {inline,pool}-{inline,pool}; do wrk http://localhost:1337/$i; done
Running 10s test @ http://localhost:1337/inline-inline
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   191.01us  122.63us   3.19ms   74.95%
    Req/Sec    27.02k     4.62k   39.31k    71.64%
  540258 requests in 10.10s, 105.62MB read
Requests/sec:  53494.35
Transfer/sec:     10.46MB
Running 10s test @ http://localhost:1337/inline-pool
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.99ms   16.00ms  97.31ms   76.06%
    Req/Sec   760.99      2.67k   16.84k    94.00%
  15167 requests in 10.06s, 2.97MB read
Requests/sec:   1507.62
Transfer/sec:    302.02KB
Running 10s test @ http://localhost:1337/pool-inline
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   193.12us  204.38us   8.53ms   97.56%
    Req/Sec    27.01k     4.90k   35.57k    61.39%
  542635 requests in 10.10s, 106.09MB read
Requests/sec:  53726.32
Transfer/sec:     10.50MB
Running 10s test @ http://localhost:1337/pool-pool
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.67ms   14.99ms  49.05ms   78.90%
    Req/Sec     3.05k     2.15k    8.12k    61.50%
  60699 requests in 10.01s, 11.87MB read
Requests/sec:   6060.98
Transfer/sec:      1.19MB
```

It's not nearly as dramatic when using `taskset --cpu-list=0` to pin my program to one CPU, supporting the idea that this has to do with bouncing between threads.

I've prepared [flame graphs](http://www.brendangregg.com/flamegraphs.html) of each configuration as a first step of figuring this out. I ran each wrk configuration with a `--duration=3600` so I could get a profile, then prepared the graphs via commands like the following:

```
$ perf record -F 99 -e cycles --call-graph=dwarf -p $(pidof serve_file) -- sleep 10 && perf script | ~/git/FlameGraph/stackcollapse-perf.pl | ~/git/FlameGraph/flamegraph.pl > profile-inline-pool.svg
```

[profiles.zip](https://github.com/tokio-rs/tokio-core/files/789193/profiles.zip)

I also tried running strace while this was happening, and it seems like there's just way too many operations. Here's a single `/inline-pool` request:

```
 <unfinished ...>
[pid 58554] <... epoll_wait resumed> [{EPOLLIN, {u32=2, u64=2}}], 1024, -1) = 1
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] accept4(6, {sa_family=AF_INET, sin_port=htons(51784), sin_addr=inet_addr("127.0.0.1")},
[16], SOCK_CLOEXEC) = 7
[pid 58554] ioctl(7, FIONBIO, [1])      = 0
[pid 58554] epoll_ctl(3, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=12, u64=12}})
= 0
[pid 58554] accept4(6, 0x7ffcbd572ef0, 0x7ffcbd572fc4, SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
[pid 58554] epoll_wait(3, [{EPOLLIN|EPOLLOUT, {u32=12, u64=12}}], 1024, 0) = 1
[pid 58554] read(7, "GET /inline-pool HTTP/1.1\r\nHost:"..., 4096) = 89
[pid 58554] open("f", O_RDONLY|O_CLOEXEC) = 8
[pid 58554] ioctl(8, FIOCLEX)           = 0
[pid 58554] fstat(8, {st_mode=S_IFREG|0664, st_size=1, ...}) = 0
[pid 58554] futex(0x7f21f28210c4, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f21f28210c0, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
[pid 58554] sendto(7, "HTTP/1.1 200 OK\r\nAccept-Ranges: "..., 204, MSG_NOSIGNAL, NULL, 0 <unfinishe
d ...>
[pid 58638] <... futex resumed> )       = 0
[pid 58554] <... sendto resumed> )      = 204
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58638] futex(0x7f21f28210f0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3,  <unfinished ...>
[pid 58638] <... futex resumed> )       = 0
[pid 58554] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58638] pread64(8,  <unfinished ...>
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3,  <unfinished ...>
[pid 58638] <... pread64 resumed> "\n", 1, 0) = 1
[pid 58554] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58638] close(8 <unfinished ...>
[pid 58554] sendto(7, "\n", 1, MSG_NOSIGNAL, NULL, 0 <unfinished ...>
[pid 58638] <... close resumed> )       = 0
[pid 58554] <... sendto resumed> )      = 1
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] read(7, "", 4096)           = 0
[pid 58638] futex(0x7f21f28210c4, FUTEX_WAIT_PRIVATE, 1063019, NULL <unfinished ...>
[pid 58554] close(7)                    = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3, [], 1024, 0)  = 0
[pid 58554] epoll_wait(3,
```

The reactor thread is doing a lot of zero-timeout epoll_wait calls. From a little digging I did into the debug logging, this has something to do with the "custom readiness queue" which indicates tasks are done. But I don't understand why it's probing for new events when it already knows it has something to do. (Is this about fairness or something?)

This is actually the faster version; it was even worse before when I created a new `CpuPool` future from the reactor for each chunk (prior to scottlamb/http-entity commit 3c5423a).

**Comment by alexcrichton** [comment]
Thanks for the thorough report! 

I'm definitely curious to dig in more here as I'd just like to know what's up. My suspicion is that there's not a whole lot we can do as architecturally these are just different choices and there may not be an underlying bug here, but I definitely wouldn't rule that out!

Out of curiosity, I wonder if this could be minimized a bit with as few libraries in play other than tokio/hyper?

**Comment by scottlamb** [comment]
> Out of curiosity, I wonder if this could be minimized a bit with as few libraries in play other than tokio/hyper?

Yeah, totally fair point. I have a simpler example now. It just creates a stream and leaks it. The server is busy-looping waiting for something to happen.

https://gist.github.com/scottlamb/53cf74c58fda4ac82c6905aef7dbff63

Credit to @mikeycgto who mentioned 100% CPU usage on an example with a timer.

**Comment by carllerche** [comment]
I haven't dug in, but off the top of my head, 10ms sounds like naggle.

**Comment by alexcrichton** [comment]
@scottlamb thanks for the minimization! That looks like an [upstream bug](https://github.com/hyperium/hyper/issues/1073). Is that related to the slowdowns you were seeing though?

**Comment by scottlamb** [comment]
Thanks!

> Is that related to the slowdowns you were seeing though?

Hmm. Partly. I mean, it just gets into the state where a stream is created but nothing has been sent on it. My original program spends some time in that state before sending chunk(s) and closing the stream, so you'd think it'd help. And the numbers in a typical trial seem a bit better now:

```
Running 10s test @ http://localhost:1337/inline-pool
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.77ms   11.35ms  48.86ms   84.83%
    Req/Sec     8.85k     6.13k   22.99k    63.50%
  176203 requests in 10.02s, 34.28MB read
Requests/sec:  17581.87
Transfer/sec:      3.42MB
```

but I was expecting under a millisecond with a low standard deviation, and this definitely isn't there. So it wasn't the whole problem.

I still see in strace these epolls with a zero timeout:

```
[pid 85243] epoll_wait(3, [], 1024, 0)  = 0
```

which, from skimming the mio code, matches this message:

```
TRACE:mio::poll: custom readiness queue has pending events
```

why is it polling when it already knows it has an event?

Anyway, I'll try to put together a new simple test case.

**Comment by scottlamb** [comment]
> I haven't dug in, but off the top of my head, 10ms sounds like naggle.

Ahh. This was the remaining piece. I patched hyper to call `set_nodelay(true)` and got this:

```
$ wrk http://127.0.0.1:1337/inline-pool
Running 10s test @ http://127.0.0.1:1337/inline-pool
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   489.63us  138.20us   2.76ms   74.78%
    Req/Sec    10.22k   559.09    11.67k    70.79%
  205379 requests in 10.10s, 40.15MB read
Requests/sec:  20335.05
Transfer/sec:      3.98MB
```

There's already a [hyper issue](https://github.com/hyperium/hyper/issues/944) about Nagle's algorithm...which I filed myself...but apparently forgot about. *sigh*

I still think that some unnecessary work is going on here (the polls with timeout 0) but I probably wouldn't have looked closely enough to notice it I was getting this performance from the start, so feel free to close if you don't think it's a problem.

**Comment by alexcrichton** [comment]
Oh great, yay!

The timeout of 0 is expected some of the time as that's what happens when a future becomes ready, but I don't *think* it should be overly impacting performance (especially with lots of concurrent connections)
