### ISSUE TITLE
Provide a non-shared reactor core that is `Send`

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio-core#179]
In a couple of cases now, I have run into the case where I have a `reactor::Core` that is only ever used by a single thread (i.e., it has no `Remote` handles). In those cases, it would be nice if the reactor was `Send`. This would make it much easier to, for example, send out structures containing clients (that internally contain reactors) to a set of worker threads, which is not currently possible.

I know adding a `Send` bound to `reactor::Core` is not feasible, since we'd want to continue to provide `Remote` handles. However, introducing a new `LocalCore` reactor might be workable. An alternative, albeit a much less backwards compatible one, is to make `reactor::Core` non-shareable (that is, `Send`), and then introduce a `SharedCore` which is `!Send` but can provide `Remote` handles.

This was motivated in part by discussions with @tikue about https://github.com/google/tarpc, where we'd like to be able to have a `Service` implementor contain a `Client`, which contains a core, so that `Services` can be sent to a pool of worker threads. He might be able to weigh in with more motivating examples.

**Comment by carllerche** [comment]
The lack of a `Send` bound isn't to support `Remote`, it's to support `Handle`. So, unfortunately, it would not be a trivial matter to provide a `Send` reactor.

**Comment by jonhoo** [comment]
Ahh, I see... I guess a `Send` reactor would need to only support directly calling `spawn()` on the reactor itself, and not even be allowed to give out `Handle`s :/

**Comment by carllerche** [comment]
Yes. At some point it may be possible for `Core` to extend `Send`, but it isn't an immediately goal. I'm going to close the issue. If you hit anything else, please open a new issue.
