### ISSUE TITLE
Calling `wait()` on `TcpStream::connect()` hangs the program

### ISSUE THREAD

**Issue by daniel-abramov** [tokio-rs/tokio-core#182]
When you create a future `TcpStream::connect()` and then call `wait()` on it, the program hangs inside the `wait()` forever and it seems that the future never resolves after that.

**Comment by dwrensha** [comment]
`Future::wait()` will block the event loop, preventing progress from being made. You should chain your computation with `and_then()` or similar. If you are at the top level of your program, you can call [`core.run()`](https://docs.rs/tokio-core/0.1.4/tokio_core/reactor/struct.Core.html#method.run).

**Comment by daniel-abramov** [comment]
> Future::wait() will block the event loop, preventing progress from being made.

Yes, `wait()` blocks the current activity until the future is resolved (returning success result or error), the problem is not blocking itself, the problem is that the future never resolves, it hangs on `wait()` and waits forever. When I use the regular chain computations using `and_then()` and run the future with `core.run()`, it works absolutely fine.

**Comment by dwrensha** [comment]
`wait()` can cause deadlock if the future depends on the event loop turning.

**Comment by carllerche** [comment]
It sounds like @dwrensha is correct. By calling wait, you are blocking the thread. Given that `Core` is single threaded, you are blocking the event loop which also processes I/O events. This means that the connect cannot resolve. The solution is to not call `wait` on the event loop.

I'm going to close the issue. If you think that there actually is a bug, please open a new one with a test case illustrating the incorrect behavior. Thanks!

**Comment by dwrensha** [comment]
(Some discussion over on futures-rs that is perhaps relevant: https://github.com/alexcrichton/futures-rs/issues/360 https://github.com/alexcrichton/futures-rs/issues/397)
