### ISSUE TITLE
Separate trait for Io-backed streams?

### ISSUE THREAD

**Issue by sunshowers** [tokio-rs/tokio-core#184]
So `Framed` ([reference](https://tokio-rs.github.io/tokio-core/tokio_core/io/struct.Framed.html)) has `get_ref` etc that return the underlying `Io`. However, once you apply a predicate like `map` to a `Framed` it is no longer possible to extract the underlying `Io`.

It would seem to be useful to have a trait that indicates a stream is `Io` backed -- perhaps `IoStream`? `IoStream` would require you to implement `get_ref` `get_mut` and `into_inner`. Then `Map<S, F>` etc could implement `IoStream` if `S` implements `IoStream`.

**Comment by alexcrichton** [comment]
We've often long felt that all the combinators (e.g. `Map`) also need methods like `get_ref`, so I'd also be totally fine adding all those suites of methods in the futures crate itself.

**Comment by alexcrichton** [comment]
I believe we've added all the requisite accessors here over time, but if anything is missing just let us know!

**Comment by sunshowers** [comment]
Thanks!
