### ISSUE TITLE
TcpStream.write_buf() signals would block incorrectly

### ISSUE THREAD

**Issue by living180** [tokio-rs/tokio-core#194]
If the buffer cannot be written, `TcpStream.write_buf()` returns a `std::io::Error` with `kind() == std::io::ErrorKind::WouldBlock`.  However, this is inconsistent with the default `AsyncWrite.write_buf()` implementation, which converts `WouldBlock` errors into `Ok(Async::NotReady)` by using `try_nb!`.  The documentation for `AsyncWrite.write_buf()` does not specify what the function should return if the write would block.  However, the `tokio-io::length_delimited` code assumes that it returns `Ok(Async::NotReady)` and fails to work correctly if it does not.  For an example, see https://gist.github.com/living180/fd1498294f3f16d5ee898343a5b2e6e3.

This could be fixed in `tokio-core` by changing `TcpStream.write_buf()` to return `Ok(Async::NotReady)` when appropriate, or in `tokio-io` by changing `AsyncWrite.write_buf()` to return `WouldBlock` errors.  I'm happy to work on a patch either way if that would be helpful; I am just not sure which direction to pursue.

**Comment by alexcrichton** [comment]
OOps, definitely a copy/paste typo!
