### ISSUE TITLE
Spammy debug logging

### ISSUE THREAD

**Issue by vorner** [tokio-rs/tokio-core#200]
When I run my tokio-based project, most of the logging output is from the tokio-core. That would be fine, but it seems like these messages are having a too high level:

```
  Apr 25 11:16:11.386 DEBG consuming notification queue
  Apr 25 11:16:11.386 DEBG updating a timeout: 0
  Apr 25 11:16:11.386 DEBG loop poll - Duration { secs: 0, nanos: 6181 }
  Apr 25 11:16:11.386 DEBG loop time - Instant { tv_sec: 144953, tv_nsec: 992238220 }
  Apr 25 11:16:11.386 DEBG loop process - 0 events, Duration { secs: 0, nanos: 10901 }
```

Would it be possible to change them (and similar) to the trace level? It seems more appropriate to me.

If it would be OK, I can provide the pull request, I just want to check first if there's no problem before I start going through all the code.

**Comment by alexcrichton** [comment]
Are you using the `env_logger` crate or perhaps another crate? This sort of debug output is invaluable for debugging issues, and in general it should be able to configure the log level per crate.

**Comment by carllerche** [comment]
Yes, those are appropriate debug level log entries for debugging tokio-core. I would recommend enabling debug output only for the crates you are trying to debug.

**Comment by vorner** [comment]
I'm using `slog` and `slog-stdlog`. And yes, I can filter the messages somehow.

Note that I don't want to get rid of the messages, only to change their severity to trace, so they still could be enabled when looking for something specific.

However, when running my application in testing environment, I like to have debug logging enabled, just in case, even when I don't have a specific problem to look for. For that, having 5 messages per one loop turn with all these details about times it took feels like a bit too much.

Maybe I look at the problem from the other side, as a user of the library while you debug the library itself more often.

**Comment by alexcrichton** [comment]
To me it makes sense to enable debug logging, but surely you're not opening an issue on every single crate in your dependency graph to change all log levels to trace? I'd expect the enabling of debug logging would be "enable debug logging in my code", not "enable debug logging in all crates"

**Comment by carllerche** [comment]
Thanks for the issue, I'm going to close this for now as I don't think that we will make any changes. The tokio-core debug log output is intended to be useful for tokio-core developers debugging tokio-core. It probably makes more sense for you to whitelist crates that you want to enable debug log output for.
