### ISSUE TITLE
PollEvented doesn’t return the Evented if it fails

### ISSUE THREAD

**Issue by Rufflewind** [tokio-rs/tokio-core#202]
While trying to resolve https://github.com/Rufflewind/tokio-file-unix/issues/2 I was tempted to allow regular files to be transparently used with Tokio by handling the EPERM error when Mio (epoll) rejects the file descriptor.  But it turns out even if I handle that, the file object is already gone.  It would be nice if `PollEvented::new` didn’t eat the Evented object on failure.

**Comment by alexcrichton** [comment]
Would [something like this help](https://github.com/tokio-rs/tokio-curl/blob/6c6eb166c976a03585d1dc96926af5e2aba3d3c3/src/unix.rs#L540-L557)?

**Comment by Rufflewind** [comment]
That would be nice, assuming there are no other situations under which EPERM could be raised (in the case of non-epoll backends).

**Comment by alexcrichton** [comment]
Oh sorty to clarify I meant that moreso of a local implementation of `Evented` rather than adding that to tokio-core itself. The handling of `EEXIST` is specific to tokio-curl so that's where the logic currently lives (as opposed to in tokio-core itself)

**Comment by Rufflewind** [comment]
Ohh, that’s what you meant.  Gotcha.

**Comment by alexcrichton** [comment]
Ok in that case I'm gonna close this, but lemme know if you have any troubles!
