### ISSUE TITLE
Putting `Core` in thread_local static

### ISSUE THREAD

**Issue by kardeiz** [tokio-rs/tokio-core#203]
I'm new to `tokio-core` and async programming in general, so please excuse my ignorance&mdash;

Is this a viable pattern for handling a core?

```rust
thread_local!(static CORE_AND_HANDLE: (RefCell<Core>, RefCell<Handle>) = {
    let core = Core::new().unwrap();
    let handle = core.handle();
    (RefCell::new(core), RefCell::new(handle))
});
```

With this I have ergonomic access to my core (as a static), and I can also use the handle even after I have put the core in a loop (e.g., `core.run(listener.incoming().for_each(|(socket, addr)| { ... }))`).

I don't know anything about the internals of this library or the implementation of `thread_local` so I don't know if this has any non-negligible overhead/unintended consequences...

**Comment by kardeiz** [comment]
Also, sorry if it is rude to ask this as an issue here. Is there a tokio Gitter or somewhere to ask tokio-related questions other than SO?

**Comment by alexcrichton** [comment]
Yeah should indeed be a possible and valid use case! One caveat I'd recommend is that TLS destructors are a little wonky sometimes so you'd probably want to manually remove the Core and destroy it youself, but other than that I've often wanted to make a library for this sort of usage :)

Also no worries! This is definitely an ok place to ask questions. You can also hop in https://gitter.im/tokio-rs/tokio

**Comment by kardeiz** [comment]
@alexcrichton thanks for the info! I've filled this out a little bit and it seems to work great for my scenario and a couple of the more simple `tokio-core` examples:

```rust
struct CoreAndHandle {
    core: RefCell<Core>,
    handle: RefCell<Handle>
}

thread_local!(static CORE_AND_HANDLE: CoreAndHandle = {
    let core = Core::new().unwrap();
    let handle = core.handle();
    CoreAndHandle {
        core: RefCell::new(core),
        handle: RefCell::new(handle)
    }
});

pub fn with_local_core<T, F: FnOnce(&Core) -> T>(cls: F) -> T {
    CORE_AND_HANDLE.with(|o| cls(&*o.core.borrow()))
}

pub fn with_local_core_mut<T, F: FnOnce(&mut Core) -> T>(cls: F) -> T {
    CORE_AND_HANDLE.with(|o| cls(&mut *o.core.borrow_mut()))
}

pub fn with_local_handle<T, F: FnOnce(&Handle) -> T>(cls: F) -> T {
    CORE_AND_HANDLE.with(|o| cls(&*o.handle.borrow()))
}
```

A couple additional questions:

1) Is 'one core per thread' a pretty common model? That is, what are the cases where you would want a `Core` in one thread and would use `Remote` to spawn into it? (I haven't thought about or researched this too much.)

2) How do I "manually remove the Core and destroy it"? It doesn't look like there is any special destroy mechanism on `Core`?

Thanks so much for your help!

**Comment by alexcrichton** [comment]
Yeah that looks pretty good!

> Is 'one core per thread' a pretty common model?

Currently, yeah, this is the recommended architecture. We would like to explore multithreaded instances of `Core` (many threads using one `Core`) but the cross platform semantics here are quite tricky and we haven't found a great way of managing that. For now we recommend for multithreaded apps to either (a) farm work to a worker thread pool (e.g. futures-cpupool) or (b) have a `Core` per thread and use something like `SO_REUSEPORT` to spread the load.

> How do I "manually remove the Core and destroy it"? 

Here you've got two options. You could either store `RefCell<Option<Core>>` or you could do something like `mem::replace(&mut core_slot, Core::new())`, basically overwriting a previous one with a new "empty" one.

**Comment by alexcrichton** [comment]
I think there's not much left here, so I'm going to close
