### ISSUE TITLE
Error handling problem

### ISSUE THREAD

**Issue by arystan-sw** [tokio-rs/tokio-core#206]
`Err()` produced by server service or server-side `codec::encode` causes client connection to hang. If I understand correctly, when protocol doesn't support encoding error frames, `Encoder::encode` produces an `Err()` which must terminate the connection. Currently, returning an `Err()` from a server service (or `Encoder::encode()`) will result in future, returned by client-side service call, being hung unresolved.

I've slightly modified the following examples from [tokio-line](https://github.com/tokio-rs/tokio-line) to demonstrate the issue:

- `streaming/examples/stdout_server.rs`
- `simple/examples/echo_client_server.rs`

Available here: https://github.com/ari7/tokio-line

**Comment by alexcrichton** [comment]
Thanks for the report! Did this intend to get filed against the tokio-line repo instead though?

**Comment by arystan-sw** [comment]
I believe this could be an issue either in `tokio-core` or `tokio-proto`. I couldn't figure out the exact cause of it, so filed here.

**Comment by alexcrichton** [comment]
Ok no worries, I think this might be most applicable to `tokio-proto` rather than tokio-core, mind opening the issue over there?

**Comment by arystan-sw** [comment]
Sure!
