### ISSUE TITLE
Discussion: strongly discourage the usage of `spawn`?

### ISSUE THREAD

**Issue by ishitatsuyuki** [tokio-rs/tokio-core#209]
The `spawn` function moves the ownership into the event loop, which means you can only control/get results with channels, that has a good amount of overhead. This also loses the ability to terminate it with Drop.

There's a few cases that this is necessary, such as how it used internally in `accept()`, but in general it should be removed from examples. The replacement is likely to be `buffered(_unordered)`.

**Comment by alexcrichton** [comment]
The `spawn` function is a primitive, something to build on. The fact that it moves ownership and runs in the background is simply a fact of the primitive. It is precisely what you want in many cases, but not necessarily what you want in others. 

The standard library doesn't discourage `thread::spawn` for the same reasons we don't discourage `spawn`, it's a design decision to use it.

**Comment by 46bit** [comment]
@ishitatsuyuki Hey, this sounds an interesting pattern. Could you show how you'd use this to build up programs?

**Comment by ishitatsuyuki** [comment]
@46bit, I haven't tried it in large scale applications yet, but basically it is what I described in the issue body. Instead of throwing things into queue (and forget), we chain it by returning additional work in `and_then`, and properly serialize Stream by buffering them. This way it's possible to Drop things by using a `select` handle.
