### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by zetok** [tokio-rs/tokio-core#211]
```
use of deprecated item: moved to the `tokio-io` crate
  --> src/main.rs:15:22
   |
15 | use tokio_core::io::{Codec, EasyBuf, Io};
   |                      ^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: moved to the `tokio-io` crate
  --> src/main.rs:15:29
   |
15 | use tokio_core::io::{Codec, EasyBuf, Io};
   |                             ^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: moved to the `tokio-io` crate
  --> src/main.rs:15:38
   |
15 | use tokio_core::io::{Codec, EasyBuf, Io};
   |                                      ^^

```
↑ those are supposed to be in the `tokio-io` create, but they're not available there:
![spectacle se4255](https://cloud.githubusercontent.com/assets/3148759/26286125/3b274ef0-3e55-11e7-9c25-cfe1133d5633.png)

**Comment by alexcrichton** [comment]
Thanks for the report! Yeah these structs don't map 1:1 with the tokio-io crate, but if you work with `Encoder` and `Decoder` the documentation there will guide you through the types involved.

**Comment by alexcrichton** [comment]
Let us know though if you've got any questions!
