### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by kaisbensalah** [tokio-rs/tokio-core#217]
After building the hello example (at https://github.com/tokio-rs/tokio-core/blob/master/examples/hello.rs, running it (using `./hello`) and testing the response using `curl http://127.0.0.1:8080`, I get the following result:

> Hello!
> curl: (56) Recv failure: Connection reset by peer

**Comment by alexcrichton** [comment]
Thanks for the report! This is expected behavior, though, because that server isn't actually talking HTTP which libcurl is expecting. As a result the `curl` invocation is going to fail (as you've seen) because there's a protocol mismatch.
