### ISSUE TITLE
wrk: socket errors

### ISSUE THREAD

**Issue by kaisbensalah** [tokio-rs/tokio-core#218]
I'm trying to benchmark my app ([test.rs](https://github.com/tokio-rs/tokio-core/files/1064704/main.rs.txt)) using wrk whose output is the following:

> Running 1m test @ http://localhost:8080
>   2 threads and 1000 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency    82.89ms  207.73ms   1.64s    91.16%
>     Req/Sec     3.16k   690.71     5.63k    71.22%
>   377105 requests in 1.00m, 34.52MB read
>   Socket errors: connect 0, read **90038**, write **287067**, timeout **634**
> Requests/sec:   6280.02
> Transfer/sec:    588.75KB

There is a lot of socket errors including read/write and timeout errors .. Yet, `curl -sSf http://localhost:8080` returns "This is Tokio!" without any error message.

What's supposed to be wrong?

**Comment by alexcrichton** [comment]
I wonder if it's `\n` vs `\r\n` in the payload? HTTP Should require `\r\n` and while curl may be lenient maybe wrk is more strict?

**Comment by kaisbensalah** [comment]
> I wonder if it's \n vs \r\n in the payload? HTTP Should require \r\n

I updated my code that way and re-tested it again, yet I'm getting the same error messages.
And .. just curious, why `\r\n` is needed?

> maybe wrk is more strict?

I don't think so - I also performed the test using another tool called `artillery`, which has finished with `ECONNRESET: 420` errors.

**Comment by alexcrichton** [comment]
I think maybe in that case this has to do with the server masquerading as HTTP/1.1 compatible, but it cuts off the connection after the first which implies lack of keepalive. In that sense I think the errors may be normal? The write errors are likely because you're writing a response without reading any data, which means that a connection may be getting closed before all the data is written.

**Comment by kaisbensalah** [comment]
> The write errors are likely because you're writing a response without reading any data, which means that a connection may be getting closed before all the data is written.

I think you're right, HTTP load balancing is not the right option for this job ..; Do you know a good tool for TCP benchmarking?

**Comment by alexcrichton** [comment]
Nah unfortunately I don't know of a great way to do TCP benchmarking other than writing your own client

**Comment by kaisbensalah** [comment]
Ah, okay. Thanks anyway - I am gonna close this issue right now.
