### ISSUE TITLE
Spawning scoped futures?

### ISSUE THREAD

**Issue by Kixunil** [tokio-rs/tokio-core#220]
Today `Handle::spawn()` requires `'static` futures. However, I believe this pattern is common:

```rust
fn main() {
    let config = load_config().unwrap();
    let core = Core::new().unwrap();
    let listening_socket = bind_socket(&core).unwrap();

    // Create listener future which spawns a future for each client.
    // Client future should be able to access config
```

Obviously, this code could use `&config` in theory, because `config` outlives everything else. However this isn't actually possible with current API. One must use `Arc<Config>` today.

How hard would it be to allow using `&config`? Was this considered?

I understand that the future might be polled by other threads after `main()` returns but I wonder if there is a way to ensure it won't.

Maybe it's not worth the effort though. That's what I'd like to know.

**Comment by alexcrichton** [comment]
A good question! Today `Core` itself does not support spawning scoped futures. This was a concious decision early on to avoid having a lifetime parameter on `Core` essentially.

You can execute non-`'static` futures with a `Core` through `core.run`, however. You can also nowadays combine this with tools like `FuturesUnordered` to efficiently spawn a large list of futures (in this case maybe `Box<Future + 'a>`. 

Does that make sense?

**Comment by Kixunil** [comment]
Why not have lifetime parameter on `Core`?

Is it possible to dynamically change contents of `FuturesUnordered` during execution? I mean, behavior equivalent to `spawn()`

**Comment by alexcrichton** [comment]
`FuturesUnordered` supports `push`, so in theory yes it can change. In practice it may require gymnatics.

A lifetime parameter on `Core` would likely not be used by 99% of users, so it's not worth the complexity.

**Comment by Kixunil** [comment]
Thank you for explanation! I wonder if it'd help to add this to docs.

**Comment by surajprak** [comment]
Can you please give a work around to run a future which is non 'static  using handle.spawn()? I don't have option to use run() as it is already getting used to run another future.

**Comment by Kixunil** [comment]
@surajpayu You can `join` futures and run them both.

**Comment by ricochet1k** [comment]
Would it be possible to add a tokio_core::reactor::lifetime module with lifetime variants of Core and Handle, and have the regular tokio_core::reactor forward to that implementation with 'static?

**Comment by carllerche** [comment]
The executor functionality of Tokio is being extracted out. This means that you will be able to plug in any arbitrary executor, including one that can support futures with lifetimes.

I'm going to close this issue now. That said, someone may want to open an issue on futures-rs to ask for a scoped `CurrentThread` executor. All the needed machinery is already present.
