### ISSUE TITLE
Release 0.1.9

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio-core#235]
Is there going to be another release before 0.2.0?  If it's not too much trouble, I would appreciate one, for I have a new crate that depends on PR #210 for its initial release, and that PR didn't make it into 0.1.8.

**Comment by alexcrichton** [comment]
Certainly! It's still gonna be awhile before 0.2!

**Comment by asomers** [comment]
Thanks so much!

**Comment by carllerche** [comment]
There is no current plan of a 0.2 release.
