### ISSUE TITLE
Abnormal program abort when using FFI with rust callbacks

### ISSUE THREAD

**Issue by ghost** [tokio-rs/tokio-core#239]
This is probably a niche use-case, but I'll document this here since I've run into an interesting issue. I'm basically setting up a Core reactor that calls out to C code via the FFI. The C code at some point calls back into rust via an extern callback which in turn attempts to get hold of a remote handle and clone it. At this point, my program terminates abnormally (OSX El Capitan, rust 1.18.0).

The gist of what I'm trying to do is here (doesn't compile, just to get an idea):

```rust
struct MyFuture {
    handle: Handle,
}

impl MyFuture {
    fn new(handle: &Handle) -> MyFuture {
        MyFuture { handle }
    }

    fn resume() {
        // Resume running C code via FFI
    }

    fn yield_() {
        // Yield control back to Rust code via FFI
    }

    fn get_result() {
    }
}

extern fn sleep(opaque_handle) -> c_int {
    let future: &MyFuture = ... // Get hold of future here from opaque_handle

    future.handle.remote().clone(); // Program terminates abnormally here
    
    future.yield_()
}

impl Future for MyFuture {
    type Item = ();
    type Error = String;

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        let ret = self.resume();
        if ret == SHOULD_YIELD {
            Ok(Async::NotReady)
        } else {
            Ok(Async::Ready(self.get_result()))
        }
    }
}

fn main() {
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let exec = MyFuture::new(&handle);
    core.run(exec);
}
```

For a little more background, I'm trying to build a tokio based scheduler on top of liblua using lua_resume / lua_yield.

**Comment by carllerche** [comment]
Is the abort caused by a panic that was not caught? When calling rust from ffi you have to catch the panic yourself.

**Comment by coderonwine** [comment]
It could be an uncaught panic, but shouldn't there be something written to stderr in that case? I'm getting no output and an exit code of 1. There's no threading code involved in either my future or lua, but something in the call to `clone` on the remote handle is causing the abort. To clarify, I can get a hold of the remote handle just fine, it's when I call clone on it that things go awry.

**Comment by coderonwine** [comment]
Ok, so assuming `future.handle.remote().clone()` is panicking and I see nothing since I'm not wrapping in `catch_unwind` - can anyone shed any light as to why the `clone` is failing in this way?

**Comment by coderonwine** [comment]
So, wrapping in a `catch_unwind` gives me the same result, i.e. abort exit code 1.

**Comment by ghost** [comment]
Embarrassingly, this was a coding mistake on my part. No problem with tokio whatsoever. Closing.
