### ISSUE TITLE
UdpFramed doesn’t send zero length UDP packets

### ISSUE THREAD

**Issue by henninglive** [tokio-rs/tokio-core#248]
[`UdpFramed` doesn’t call `send_to()`](https://github.com/tokio-rs/tokio-core/blob/645ae7051d08221cbd44ad1211eac8af2f0b6c67/src/net/udp/frame.rs#L79-L113) on the underlining `UdpSocket` if no data is written to the send buffer by the `UdpCodec`. `UdpSocket` sends zero length packets as expected.

**Comment by alexcrichton** [comment]
Weird I didn't know 0-length packets were a thing! Shouldn't be too hard to fix though! Would you be interested in sending a PR for this?

**Comment by henninglive** [comment]
Yeah, sure.
