### ISSUE TITLE
reactor::interval tests broken on Windows because of std::time::Instant rounding errors

### ISSUE THREAD

**Issue by henninglive** [tokio-rs/tokio-core#249]
Adding/subtracting a `std::time::Duration` to an `std::time::Instant` may give rounding errors on Windows, this breaks some tests on my system. This happens because on Windows, [`Instant`](https://github.com/rust-lang/rust/blob/b413f34087d913b80cf432a66d05ec5be11f3515/src/libstd/sys/windows/time.rs) is implemented as a 64bit count captured from a performance counter with system dependent frequency, while the shared [`Duration`](https://github.com/rust-lang/rust/blob/b413f34087d913b80cf432a66d05ec5be11f3515/src/libstd/time/duration.rs) implementation uses the timespec format. When adding/subtracting a `Duration`, the sub second fraction is multiplied by the frequency, giving us number of cycles, rounded down. For reference, `QueryPerformanceFrequency()` returns `1753867` on my system.

Test failures:
```
Running target\debug\deps\tokio_core-6b419814f59f26e4.exe

running 23 tests
test reactor::interval::test::norm_next ... FAILED
test reactor::interval::test::fast_forward ... FAILED
test reactor::interval::test::large_skip ... ok

failures:
---- reactor::interval::test::norm_next stdout ----
        thread 'reactor::interval::test::norm_next' panicked at 'assertion failed: `(left == right)` (left: `Instant { t: 309192835979 }`, right: `Instant { t: 309192835980 }`)', src\reactor\interval.rs:141

---- reactor::interval::test::fast_forward stdout ----
        thread 'reactor::interval::test::fast_forward' panicked at 'assertion failed: `(left == right)` (left: `Instant { t: 309208561643 }`, right: `Instant { t: 309208561644 }`)', src\reactor\interval.rs:153


Running target\debug\deps\interval-58fb2ca500b2ecba.exe

running 2 tests
test single ... FAILED
test two_times ... ok

failures:
---- single stdout ----
        thread 'single' panicked at 'assertion failed: start.elapsed() >= dur', tests\interval.rs:25
```

**Comment by alexcrichton** [comment]
Hm I think the start time for these tests was actually a little off, mind testing https://github.com/tokio-rs/tokio-core/commit/a4e947fba0c50d60fcd01e9d3f6a9cfe990e251d and see if it works?

**Comment by henninglive** [comment]
It’s still broken, the problem is rounding when doing math with `Instant` and `Duration`, changing the start time is not going fix that.

The first test that fails is essentially asserting this:
```rust
use std::time::{Instant, Duration};

let tm = unsafe { std::mem::transmute::<_, Instant>(0i64)};
let a = (tm + Duration::from_millis(1)) + Duration::from_millis(10);
let b = tm + Duration::from_millis(11);

//Fails, 19291 != 19292
assert_eq!(a, b);
```
This is not guaranteed to be true on windows because of rounding when converting `Duration` to cycle counts so it can be added/subtracted to an `Instant`.
```
freq = 1_753_867
tm = 0

(1_000_000/1_000_000_000)*freq = 1753.867
(10_000_000/1_000_000_000)*freq = 17538.67
a = (tm + trunc(1753.867)) + trunc(17538.67) = 19291

(11_000_000/1_000_000_000)*freq = 19292.537
b = tm + trunc(19292.537) = 19292
```

**Comment by alexcrichton** [comment]
Ah sorry about that, got mixed up as to which tests these were referring to! I think this should be fixed in https://github.com/tokio-rs/tokio-core/commit/e0b751b0137fb1cf572e07fa6463f5f984f7e9a7
