### ISSUE TITLE
Document example with stateful process

### ISSUE THREAD

**Issue by kpcyrd** [tokio-rs/tokio-core#257]
hey :)

I'm still trying to wrap my head around tokio and I have a simple application working. I'm accepting requests with tokio-proto and tokio-service and successfully reply to them. My problem is:

I'm listening for requests with tokio-uds in one thread, and also with tcp in another thread. I'd like to introduce a third thread (for simplicity) that both of my servers can communicate with, preferably over mpsc returning a future reply. This third thread would manage the state machine that is shared between all clients.

I'm having issues creating a service with an mpsc sender, an example would be appreciated, [everything](https://github.com/tokio-rs/tokio-core/tree/master/examples) I found so far is pretty much stateless. :)

**Comment by alexcrichton** [comment]
Sounds like a good idea to me, thanks for the idea!

I wonder, would a simple "database" work here? Maybe like a line based protocol with like `GET $KEY` and `SET $KEY $VALUE`? The shared state in this case would be the hashmap, but I'm not sure if that's "enough" shared state?

**Comment by kpcyrd** [comment]
@alexcrichton yes, that's what I'm think about :) Ideally the hashmap would be global in a way that I can create two connections, send `SET foo bar` and then get the value back on the other connection with `GET foo`.
