### ISSUE TITLE
Add Debug impl for Timeout

### ISSUE THREAD

**Issue by casey** [tokio-rs/tokio-core#259]
Noticed that it wasn't present when I tried to derive debug for a struct of mine that contained it. Would be great to have a tokio-provided implementation!

**Comment by casey** [comment]
Also, I think the `missing_debug_implementations` lint will catch this kind of thing

**Comment by alexcrichton** [comment]
Sounds like a great idea to me! Would you be willing to send a PR?

**Comment by casey** [comment]
Yup! See #263
