### ISSUE TITLE
Support cancellation uniformly in higher-level abstractions

### ISSUE THREAD

**Issue by taralx** [tokio-rs/tokio-core#26]
IO cancellation is particularly important when dealing with composed network operations, e.g. timeouts and predictive operations. The web is currently dealing with this:

https://github.com/whatwg/fetch/issues/20
https://github.com/whatwg/fetch/issues/27

As far as I can tell, cancellation needs to be a primitive of the IO system if it is to function correctly, so IMO it is timely to consider at this time.

**Comment by taralx** [comment]
For example, the io operations don't support any kind of cancellation, even if they could take a long time.

**Comment by carllerche** [comment]
Thanks for the report. Cancellation as a concept is already strongly built into the core abstractions. You can read more about it here under the cancellation section: http://aturon.github.io/blog/2016/09/07/futures-design/

There are places where it's not fully integrated, but it would be more an isolated implementation detail of a component and not a fundamental problem.
