### ISSUE TITLE
Nicer {TcpSocket, UdpSocket}::bind()

### ISSUE THREAD

**Issue by imp** [tokio-rs/tokio-core#260]
The `UdpSocket::bind()` from `socket::net` is easier to use due to accepting anything that is `ToSocketAddrs`

```rust
pub fn bind<A: ToSocketAddrs>(addr: A) -> io::Result<UdpSocket>
```

while that of the `tokio_core::net` wants only `SocketAddr`
```rust
pub fn bind(addr: &SocketAddr, handle: &Handle) -> io::Result<UdpSocket>
```
It may be friendlier for consumers to emulate `std::net` interface.

Same goes for the `TcpSocket`

**Comment by carllerche** [comment]
Thanks for the report.

We cannot take `ToSocketAddrs` as an argument because it is a blocking API. Aka, it implies DNS resolution in a blocking (block the thread fashion).
