### ISSUE TITLE
Document that sync APIs should not be backed by async implementations

### ISSUE THREAD

**Issue by mathstuf** [tokio-rs/tokio-core#265]
Due to Rust's thread safety guarantees, synchronous APIs cannot be backed by an async implementation with an embedded `Core` object due to the `!Sync + !Send` which it forces on the synchronous structure doing the internal "de-asyncification".

Tokio's documentation should discourage crates from making synchronous APIs by just piecing together an async implementation together with a local (usually hidden) `Core` instance.

**Comment by alexcrichton** [comment]
Thanks for the report! This is something that we don't actually want to document, however, because we precisely want to use async apis to back sync implementations! The management of `Core`, however, is certainly something we we are looking to improve.

You may be interested in tokio-rs/tokio-rfcs#3 which I believe greatly improves this by avoiding the need for a `Core` in most situations.

**Comment by mathstuf** [comment]
Yeah, I'm not thrilled about that either (mainly due to implicit runtime stuff, but maybe it won't be so bad). I forsee having to open many issues related to this in the future, but it'd be nice to document that synchronous APIs should be Send (and ideally Sync too) somewhere. Because otherwise it means you can't use that API through rayon (where I currently get blocked trying to used various crates doing the internal Core).

**Comment by alexcrichton** [comment]
Certainly yeah! We should definitely document that "best practice" is to make sure that everything is `Send`. If you've got concerns about the RFC, though, please feel free to leave a comment!

**Comment by mathstuf** [comment]
I left my comments on the first version of that RFC. Others also brought up similar concerns, but they seem to have been deemed less important than the ergonomics goal. I did have one or two points that didn't seem to have made it to the new RFC. I'll reraise them.

**Comment by alexcrichton** [comment]
Ok, thanks!
