### ISSUE TITLE
No documentation on combining TcpListener with non-TCP tokio types

### ISSUE THREAD

**Issue by alexchandel** [tokio-rs/tokio-core#278]
Is it possible to run a TcpListener & another tokio type (like tokio-process, or reading from a pipe) on the same Core object?

The examples in the documentation, like from [here](https://tokio.rs/docs/getting-started/pipeline-server/), only ever run a single TcpListener:
```rust
fn serve<S>(s: S) -> io::Result<()>
    where S: NewService<Request = String,
                        Response = String,
                        Error = io::Error> + 'static
{
    let mut core = Core::new()?;
    let handle = core.handle();

    let address = "0.0.0.0:12345".parse().unwrap();
    let listener = TcpListener::bind(&address, &handle)?;

    let connections = listener.incoming();
    let server = connections.for_each(move |(socket, _peer_addr)| {
        let (writer, reader) = socket.framed(LineCodec).split();
        let service = s.new_service()?;

        let responses = reader.and_then(move |req| service.call(req));
        let server = writer.send_all(responses)
            .then(|_| Ok(()));
        handle.spawn(server);

        Ok(())
    });

    core.run(server)
}
```

Using TcpServer from tokio-proto is out of the question here, since it only runs TCP services & blocks the thread.

**Comment by alexchandel** [comment]
From IRC I've heard it could be done by spawning `server` with `handle.spawn(server)`, rather than running it. Is that right? Could that feature more prominently in the documentation somewhere?

**Comment by alexcrichton** [comment]
Yeah I think this is mostly a documentation issue, and this should definitely be handled in the coming weeks as we revamp the documentation. I don't think we'll gain a lot from having a specific bug like this open, though, so I'm going to close this.
