### ISSUE TITLE
Allow timers to be reset without a new deadline

### ISSUE THREAD

**Issue by sfackler** [tokio-rs/tokio-core#280]
I've recently refactored tokio-io-timeout to reuse the same `Timeout` rather than repeatedly creating and destroying them. When I need to "turn off" the timeout, I can use reset, but that requires me to provide a new deadline. It'd be nice if there was a variant that didn't, and simply unregistered the timeout from the timer heap.

https://github.com/sfackler/tokio-io-timeout/blob/master/src/lib.rs#L48

**Comment by sfackler** [comment]
Similarly, it'd be nice if you could create a `Timeout` without a deadline.

**Comment by alexcrichton** [comment]
Seems plausible to me to add!
