### ISSUE TITLE
Compress and connect examples doesn't work together

### ISSUE THREAD

**Issue by ericho** [tokio-rs/tokio-core#296]
I'm seeing a behavior trying to run the `compress` example, If I follow the step described in the example to use the command:

```
echo test | cargo run --example connect 127.0.0.1:8080 | gunzip
```

Then there's no response from the compress example, however if I run:

```
echo "something" | nc 127.0.0.1 8080 | gunzip
```

Then everything works fine. I was trying to debug as a learning task but I got lost. Also, i'm not sure if this is a bug or an expected behavior. 

I'll appreciate any advice to debug this issue :smile:

**Comment by alexcrichton** [comment]
Thanks for the report, and nice catch!
