### ISSUE TITLE
Rename `Loop`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#3]
The term `Loop` is a bit vague for role played by the type. The `Loop` type listens for event notifications, then dispatches the event notifications to their targets. It is a `Loop` in that it repeats this job until it is shutdown.

Three options discussed are:

**IoLoop**

Pro: It references I/O, which is the primary role of the component.
Con: It does more than I/O, so `IoLoop` doesn't really match the scope of the component.

**EventLoop**

Pro: Better describes that it is doing and the term has been used in other async I/O libraries, so there is prior art for it.
Con: `EventLoopHandle` is long

**Reactor**

Pro: Not too long and describes what the component is actually doing. There is also plenty of prior art for the term "reactor"
Con: The term comes with some baggage in that `Reactor` already has meaning to some people that isn't necessarily related to what our component does.

**Comment by aturon** [comment]
I definitely agree that `Loop` is not ideal given where things have ended up.

I would prefer to stay away from `Reactor`, but think the other two are both fine. For the `Handle` issue, we might be able to rearrange the names to avoid that suffix.

**Comment by carllerche** [comment]
I would prefer `EventLoop` if it is possible to avoid `EventLoopHandle`

**Comment by alexcrichton** [comment]
Proposal:

``` rust
mod tokio_core {
    mod reactor {
        struct Core { ... }
        struct Pin { ... }
        struct Handle { ... }
    }

    mod net {
        struct TcpStream { ... }
        struct TcpListener { ... }
        struct UdpSocket { ... }
    }

    mod io {
        type IoFuture;
        type IoStream;

        fn read_to_end() { ... }
        fn write_all() { ... }
        // ...
    }

    mod timer {
        struct Timeout { ... }
    }

    mod channel {
        struct Sender { ... }
        struct Receiver { ... }

        fn channel() -> (Sender, Receiver) { ... }
    }
}
```

thoughts?

**Comment by aturon** [comment]
Strong :+1: on the proposed organization.

**Comment by carllerche** [comment]
Sounds good to me.

Minor bikeshed (take it or leave it, i don't have a huge opinion):

What about `Pin` -> `Local`?

**Comment by alexcrichton** [comment]
For reference, PR with final proposal at #13
