### ISSUE TITLE
Problem with global variable lifetime in a single threaded context.

### ISSUE THREAD

**Issue by George3d6** [tokio-rs/tokio-core#300]
I have the following code:

```
fn main() {
    let status_map = HashMap::new();

    let listener = TcpListener::bind(&"127.0.0.1:1478".parse().unwrap()).unwrap();
    let receptor = listener.incoming().for_each(move |stream| {
        let (reader, _) = stream.split();
        let conn = io::read_to_end(reader, Vec::new()).then(|res| {
            let entry = status_map.entry('test').or_insert(vec![1]);
            Ok(())
        });
        current_thread::spawn(conn);
        Ok(())
    })
    .map_err(|err| {
        println!("IO error {:?}", err);
    });

    current_thread::run(move |_| {
        current_thread::spawn(receptor);
    });
}
```

Which refuses to compile with the error `status_map does not live long enough`

Seeing as status_map is declared in the outermost scope and the server is multithreaded, why would this happen ? Is there a way to achieve what I'm trying (accessing a variable declared inside main from inside the Future object).

**Comment by carllerche** [comment]
`current_thread::spawn` requires a `'static` bound. This is because there is no guarantee that the stack stays around.

In your example, it looks like you can add some `move` statements to your callbacks to move `status_map` into the inner closure, then it should work.
