### ISSUE TITLE
TaskRc being accessed on task it does not belong to

### ISSUE THREAD

**Issue by szagi3891** [tokio-rs/tokio-core#31]
In the example : https://github.com/tokio-rs/tokio-core/blob/66cff8e84b0bdbdc716fe1cd715363aa7e79aefa/examples/echo.rs

is there line :

```
let pair = futures::lazy(|| futures::finished(socket.split()));
```

I replace it on

```
let pair = futures::finished(socket.split());
```

And I get error :

```
     Running `target/debug/examples/echo`
Listening on: 127.0.0.1:8080
thread 'main' panicked at 'TaskRc being accessed on task it does not belong to', /home/grzegorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.1/src/lib.rs:206
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/examples/echo` (exit code: 101)
```

The current state is wrong because the bug manifests itself in runtime.

**Comment by szagi3891** [comment]
cc: @carllerche @taralx @hjr3 - I made issue that did not escape topic

**Comment by szagi3891** [comment]
Mayby split function should return (ReadHalf<Self>, WriteHalf<Self>) as future ?

**Comment by taralx** [comment]
This is actually a futures-rs issue. I've created an issue there.

**Comment by alexcrichton** [comment]
Indeed! What's happening here is that once you've split an I/O object, both the returned handles are tied to the current task. In the echo server, though, a new task is spawned which causes this panic. I'm going to close this in favor of alexcrichton/futures-rs#148, but thanks for the report!

**Comment by szagi3891** [comment]
Also thank you :)
