### ISSUE TITLE
Updating from 0.1.12 to 0.1.14 breaks code

### ISSUE THREAD

**Issue by ParadoxSpiral** [tokio-rs/tokio-core#310]
Hi, I haven't investigated this much yet, but running a cargo update that does the following breaks my code (I've already determined that the serde/synapse-rpc updates are not at fault):
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding arrayvec v0.4.7
    Updating cc v1.0.5 -> v1.0.6
      Adding crossbeam-deque v0.3.0
      Adding crossbeam-epoch v0.4.0
      Adding crossbeam-utils v0.2.2
      Adding memoffset v0.2.1
      Adding nodrop v0.1.12
      Adding scopeguard v0.3.3
    Updating serde v1.0.28 -> v1.0.29
    Updating serde_derive v1.0.28 -> v1.0.29
    Updating syn v0.12.13 -> v0.12.14
    Updating synapse-rpc v0.1.9 -> v0.1.10
      Adding tokio v0.1.3
    Updating tokio-core v0.1.12 -> v0.1.14
      Adding tokio-executor v0.1.0
    Updating tokio-io v0.1.5 -> v0.1.6
      Adding tokio-reactor v0.1.0
      Adding tokio-threadpool v0.1.0
```

To repro:
- `$ git clone https://github.com/Luminarys/synapse.git && cd synapse && cargo run`
- `$ git clone https://github.com/ParadoxSpiral/axon.git && cd axon && cargo update && cargo run`
- Enter 127.0.0.1 into axon, hit enter.
- The connection should be established immediately, but instead a Timeout of 10 seconds is triggered, even though the synapse debug output shows that a connection has been established.

The relevant code is [this](https://github.com/ParadoxSpiral/axon/blob/master/src/rpc.rs#L84-L103)
Anyone got an idea of what might have happened here?

**Comment by carllerche** [comment]
Thanks for the report. I was not able to reproduce the issue locally on OS X. Would you mind providing a bit more info on the environment?

**Comment by carllerche** [comment]
Also, is there a way to repro w/o the terminal UI? Maybe that is what is tripping me up.

**Comment by ParadoxSpiral** [comment]
[Here's](https://0x0.st/sm5m.mkv) a video of the behaviour, first how it should be, then what happens after an update.
Note that eventually (after the timeout of 10 seconds) axon does get notified that it was connected, ~~but does not receive any RPC messages (the list of torrents/trackers is empty).~~ and only occasionally receives messages (via tokio streams implemented by rust-websocket) at the very start.

**Comment by carllerche** [comment]
Here is the problem: https://github.com/ParadoxSpiral/axon/blob/master/src/rpc.rs#L61-L62

It is not safe to use `Core` instances across threads. It just happened to work to date by luck.

**Comment by ParadoxSpiral** [comment]
Oh, well then, sorry for the noise I guess :<
