### ISSUE TITLE
Backport critical fix in PollEvented from tokio crate

### ISSUE THREAD

**Issue by glebpom** [tokio-rs/tokio-core#317]
Hi,

https://github.com/tokio-rs/tokio/pull/250 contains the critical fix in `PollEvented`. This fix should also be applied to `tokio-core` because this code was backported from `tokio` crate recently

**Comment by carllerche** [comment]
Thanks for the reports. Have you verified that the issue is present here?

**Comment by glebpom** [comment]
Absolutely. The missprint is in https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/poll_evented2.rs
In fact, we have observed a high CPU usage on slow connections after upgrading to latest version

**Comment by carllerche** [comment]
Thanks. I'll try to get that fix released in a bit.
