### ISSUE TITLE
Consider making ReadHalf and WriteHalf implement poll(_read) and poll(_write)

### ISSUE THREAD

**Issue by fables-tales** [tokio-rs/tokio-core#32]
I'm currently working on a project which converts a `TcpStream` into a `Stream` of u8s via using poll_read() to implement the poll method of the `Stream`. The problem being that creating this stream consumes the TcpStream, meaning that once I've read data out of the socket, I'm unable to write things back. If I were able to poll() the readhalf and writehalf I'd be able to implement the byte stream in terms of the split() of the socket, and be able to write in the eventual for_each call.

Is this something that can be done? I'd be up for implementing it if it seems tractable.

Thanks 👍

**Comment by alexcrichton** [comment]
Good idea!
