### ISSUE TITLE
Getting a Illegal instruction segfault on arm (Raspberry Pi 1)

### ISSUE THREAD

**Issue by weiznich** [tokio-rs/tokio-core#324]
(I'm quite unsure where to report this)

I'm trying to run some future related code on an old raspberry pi 1. After cross compiling a binary construction a reactor and spawning a future on it the program segfaults with an illegal hardware instruction error. 
Programs without a reactor are running fine.

Example code:
```rust
extern crate tokio_core;
extern crate futures;

fn main() {
   let core = tokio_core::reactor::Core::new().unwrap();
       core.handle().spawn(futures::future::ok(()));
    println!("Hello, world!");
}
```

Versions:
* Rustc: `rustc 1.25.0 (84203cac6 2018-03-25)`, `rustc 1.27.0-nightly (79252ff4e 2018-04-29)`
* tokio_core: 0.1.17
* futures: 0.1.21
* target: arm-unknown-linux-musleabihf

**Comment by carllerche** [comment]
I would think that this is a rust issue and should be reported on rust-lang/rust?
