### ISSUE TITLE
`poll_read()` returns futures::poll::Async which is a private type?

### ISSUE THREAD

**Issue by fables-tales** [tokio-rs/tokio-core#34]
``` rust
src/socket_stream.rs:25:32: 25:53 error: mismatched types [E0308]
src/socket_stream.rs:25         let ready: Async<()> = self.read.poll_read();
                                                       ^~~~~~~~~~~~~~~~~~~~~
src/socket_stream.rs:25:32: 25:53 help: run `rustc --explain E0308` to see a detailed explanation
src/socket_stream.rs:25:32: 25:53 note: expected type `futures::Async<()>`
src/socket_stream.rs:25:32: 25:53 note:    found type `futures::poll::Async<()>`
```

My file contains a `use futures::Async` declaration, and I was having trouble pattern matching the `ready` variable like this:

``` rust
match ready {
  Async::Ready(_) => ...
  Async::NotReady => ...
}
```

it turns out that for some reason (related to this maybe? http://alexcrichton.com/futures-rs/src/futures/src/poll.rs.html#24) that the type returned here is `futures::poll::Async`. I tried changing the type to `use futures::poll::Async;` but that resulted in

```
src/socket_stream.rs:5:5: 5:25 error: module `poll` is private
```

Is this the correct usage?

As a work around I'm using `if ready.is_ready()`, but I think the match might be preferable?

**Comment by aturon** [comment]
Hmm, something is amiss with that error. In particular, `futures::Async` is just a public re-export of `futures::poll::Async`, so a mismatch between then shouldn't be possible...

Any chance you can make a small example that reproduces the problem, or otherwise put up the code somewhere?

**Comment by fables-tales** [comment]
this turned out to be an issue with pulling both tokio and futures from github, changing futures to 0.1 in my Cargo.toml fixed this.
