### ISSUE TITLE
PollEvented::need_read wakes up the task immediately

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#44]
It looks like calling `PollEvented::need_read` will cause the current task to be unparked immediately. This is unexpected behavior and can cause a task to get into an infinite wakeup loop if `need_read` is called without a `poll_read` guard before it.

**Comment by carllerche** [comment]
It also makes me wonder if the `need_read` bit if going through a less than optimal code path since it looks like it sends a message over a channel to the event loop even though the task is running on the event loop.

**Comment by Ralith** [comment]
I encountered this problem after the docs lead me to believe that `PollEvented::poll_read` and `PollEvented::need_read` have very similar side effects when the source is not readable:

`poll_read`:

> If this stream is not ready for a read then NotReady will be returned and the current task will be scheduled to receive a notification when the stream is readable again.

`need_read`:

> The flag indicating that this stream is readable is unset and the current task is scheduled to receive a notification when the stream is then again readable.

There's also no obvious mention that `poll_read` is required. My application uses its own methods to test whether any data is available, so I had omitted it as redundant.

**Comment by alexcrichton** [comment]
Oh right, yes! This was a "bug" which is actually intended behavior right now. As @Ralith pointed out it's required to call `poll_read` if you're calling `need_read` (to disambiguate races). The original intention was that you could call one or the other but current semantics require that you use both.

I'll update the docs.

> it looks like it sends a message over a channel to the event loop even though the task is running on the event loop.

It almost does, but there's [a short cut](https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L502-L523) if we're on the event loop at the last second.
