### ISSUE TITLE
Yielding execution on the loop

### ISSUE THREAD

**Issue by NeoLegends** [tokio-rs/tokio-core#45]
When writing loops that shall be run for a long time on the event loop, it would be nice if we could yield execution to the loop at a certain point. E.g. with a using `Handle::yield()`.

**Comment by carllerche** [comment]
Yielding to the loop is part of the `futures`crate. It is already possible by doing something like:

``` rust
task::park().unpark();
return Ok(Async::NotReady);
```

I created an issue in the futures repo to make it easier: alexcrichton/futures-rs#177.
