### ISSUE TITLE
Add io::lines

### ISSUE THREAD

**Issue by oberien** [tokio-rs/tokio-core#53]
As discussed in the [Chat example PR](/41) it would be nice to have a function in tokio-core, which takes a `BufRead` and returns `Stream<Item=String, Error=io::Error>`. This would make it easy to read lines asynchronously from a `TcpStream`/`Read`.

On the other hand side, there is [tokio-line](https://github.com/tokio-rs/tokio-line), a repository based on the idea of line-based asynchronous handling. Adding such a method to tokio-core would definitely interfere with the idea of tokio-line.

/cc @alexcrichton @carllerche

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
