### ISSUE TITLE
Cancel for timeouts

### ISSUE THREAD

**Issue by ustulation** [tokio-rs/tokio-core#56]
Hey guys, it is natural to think that timers and cancellation go hand in hand. So if i schedule a `tokio_core::reactor::Timeout` like

```
let to = Timeout::new(Duration::from_secs(2), &handle).unwrap();
handle.spawn(to); // spawn into a running event loop
```

is there a way i can cancel this ?

To explain more - i have a `Complete` stored and will fire it if i get something within a time period. If i don't I want to drop it, indicating that it was cancelled. So i spawn a corresponding `Timeout`. However if i do get that _something_ before the timeout then i will fire `Complete` and would also to cancel the timeout.

**Comment by alexcrichton** [comment]
Hello! Right now to cancel a future it's signaled typically via drop. If you spawn a future you can't cancel it (aka exactly like above), but there are other methods of transmitting cancellation (e.g. via a oneshot plus `select`) which can be used to signal a drop.

Does that make sense?

**Comment by ustulation** [comment]
Ah right - ya using select would do i guess. Thanks !
