### ISSUE TITLE
The return type of tokio_core::io::read is not exposed

### ISSUE THREAD

**Issue by spinda** [tokio-rs/tokio-core#59]
https://github.com/tokio-rs/tokio-core/blob/master/src/io/mod.rs#L47

`ReadToEnd` and `ReadExact` are exposed, for example, but `Read` is not, making it impossible for code outside of tokio to refer to the return type of `tokio_core::io::read`.

**Comment by ghost** [comment]
Thanks for the report, this should be addressed by pull request #55.

**Comment by alexcrichton** [comment]
Indeed, fixed in #55
