### ISSUE TITLE
Consider moving functions off of `LoopHandle` & `LoopPin`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#6]
I will use connecting a `TcpStream` as an example, but the idea applies to a number of other functions on `LoopHandle`.

The current primary API for connecting a TCP stream is to use `LoopHandle::tcp_connect` or `LoopPin::tcp_connect` (which doesn't currently exist, but I believe the current plan is to implement it). There also exists `TcpStream::connect_stream` which allows for more advanced socket configuration.

IMO there are two drawbacks to this strategy.

1) It creates a scattered API. When a user wants to discover how to establish a TCP stream, they will most likely first look at `TcpStream`. They will see `TcpStream::connect_stream` and one conclusion is that this is the way to connect a `TcpStream`. They will have to know to look at either `LoopHandle` or `LoopPin` depending on their case.

2) It is not an extensible pattern. The goal of tokio-core is to allow any `mio::Evented` type to work with `tokio_core::Loop`. Imagine `struct TimerFd`, a wrapper around Linux's timerfd feature. This library would not be able to easily implement `LoopHandle::create_timer()`, and will most likely fallback on the `TimerFd::create(&loop_handle)` API.

I propose to keep the functions on `LoopHandle` minimal in favor of keeping constructor functions on the types themselves:

``` rust
struct TcpStream {
    fn connect(addr: &SocketAddr, event_loop: &LoopHandle) -> IoFuture<TcpStream> {
        // ...
    }
}
```

This leaves open the question of how to differentiate between `LoopHandle`, which must return an `IoFuture` and `LoopPin` which can complete the operation immediately.

To handle this, two functions are needed:

``` rust
struct TcpStream {
    fn connect(addr: &SocketAddr, event_loop: &LoopPin) -> io::Result<TcpStream> {
        // ...
    }

    fn connect_on(addr: &SocketAddr, event_loop: &LoopHandle) -> IoFuture<TcpStream> {
        // ...
    }
}
```

However, `LoopPin` refers to the currently running `Loop` (this is due to the fact that it cannot be sent). So, one possible simplification would be to omit `LoopPin` in the first function in favor of having a way to retrieve it from a thread local:

``` rust
struct TcpStream {
    fn connect(addr: &SocketAddr) -> io::Result<TcpStream> {
        // ...
    }

    fn connect_on(addr: &SocketAddr, event_loop: &LoopHandle) -> IoFuture<TcpStream> {
        // ...
    }
}
```

In this case, if `TcpStream::connect` is called off of an event loop, the function would either return an error or it could always return `NotReady` until it is operated on from within the context of a running `Loop`.

**Comment by aturon** [comment]
OK, so I definitely buy that these functions should all be "constructors" on e.g. `TcpStream`, for all of the reasons @carllerche is saying.

It's not clear to me how important it is to get an immediate result when you have a `LoopPin`, rather than getting a future. Is there a good use case?

If not, I'd propose that we have `LoopPin` implement something like `AsRef<LoopHandle>` and then have:

``` rust
struct TcpStream {
    fn connect<H: AsRef<LoopHandle>>(addr: &SocketAddr, handle: H) -> IoFuture<TcpStream> {
        // ...
    }
}
```

**Comment by alexcrichton** [comment]
I agree that these should all be constructors on the types, but I agree with @aturon that we may not want pin/handle distinctions right now. We can already extract a handle from a pin, so I'd be tempted to _only_ provide the `LoopHandle` version of the functions for now. We could eventually soup up with pin operations or with `AsRef<LoopHandle>`, but I'm tempted to avoid for now.

**Comment by carllerche** [comment]
The direction of `AsRef<LoopHandle>` seems good.

Regarding the future, why does there need to be a future returned in the first place? `tokio::TcpStream` could return immediately and "encapsulate" the future logic internally, not returning readiness until it is connected.

**Comment by sbstp** [comment]
How would you catch connection errors if the `TcpStream` is returned directly? Should the first call to a method of the `TcpStream` fail? What if you call a method before the stream knows if the connection worked?

```
let mut sock = TcpStream::connect("rust-lang.org", 80).unwrap();
sock.peer_addr(); // NotReady ?
```
