### ISSUE TITLE
tokio_core::io::Io should be split into async read/write traits

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/tokio-core#62]
It appears to be idiomatic in tokio to take ownership of IO handles when transforming them, and therefore to split bidirectional channels into two separate objects. The existing monolithic `Io` abstraction doesn't play well with this, but could be split into separate traits respectively providing `poll_read` and `poll_write`, and perhaps `need_read` and `need_write` if necessary. These could be the traits suggested in #61.

**Comment by alexcrichton** [comment]
Thanks for the report! I think that we'll still want the `Io` trait for a method like `split` (if we keep it), but otherwise I'm 👍 on splitting into separate async read/write halves

**Comment by jpastuszek** [comment]
Some implementations require only one data flow direction. For example syslog processing would only require reading. Current IO and Codec traits require write support as well, so Codec::decode() needs to be unimplemented!() and I generally need more mutability (for IO: Write requirement) then should be necessary.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
