### ISSUE TITLE
Allow RawFd Registration and Notification

### ISSUE THREAD

**Issue by aajtodd** [tokio-rs/tokio-core#63]
There should be some way to re-use the event loop to run additional IO (e.g. from a raw fd). 

This seems to be the closest thing to adding a new arbitrary stream to the event loop but it's private: https://github.com/tokio-rs/tokio-core/blob/master/src/net/tcp.rs#L227

That of course doesn't answer the other side of the coin of some kind of notification mechanism for when that fd is ready for read/write. I would imagine this looks something like the now deprecated mio event loop API but that could be debated.

Motivation: You want to build a service with the higher level primitives but you also need to integrate with additional libraries (e.g. an ffi library that you run the IO for the socket) or have low level control over the IO of another socket. More concretely maybe I want to build an IPC service with tokio-service/proto and need to integrate some library into the event loop somehow.

As it stands you could of course run a second event loop in another thread around mio primitives but that seems less than ideal as tokio-core is already running such a loop.

It looks as though mio is moving towards deprecating any event loop abstraction and just providing the common poll/registration interface which makes a lot of sense. As such I think this would belong in tokio-core as it now provides the event loop abstraction.

**Comment by alexcrichton** [comment]
Thanks for the report! This should actually already be possible today, in fact. The [`PollEvented`](https://tokio-rs.github.io/tokio-core/tokio_core/reactor/struct.PollEvented.html) type is the workhorse here and is generic over the mio [`Evented`](https://docs.rs/mio/0.6.0/mio/trait.Evented.html) trait. On Unix mio also exports the [`EventedFd`](https://docs.rs/mio/0.6.0/mio/unix/struct.EventedFd.html) type which allows you to then work with arbitrary file descriptors.

You can see an example of this in [`tokio-curl`](https://github.com/tokio-rs/tokio-curl/blob/533562345d6ab680c8b786d7e262563d88e06ffe/src/unix.rs#L458-L482) where libcurl is the one giving us sockets and when we register them with the event loop.

Does that all make sense? And does it all work for your use case?

**Comment by aajtodd** [comment]
Thanks @alexcrichton. Yes, I believe that looks like what I want (and more obvious now that you point it out, mapping to futures wasn't immediately clear). 

I'll need to study the tokio-curl example more but if I understand this you would implement Future for some data structure that holds the socket, spawn that future onto the event loop, and when it's poll is called, poll the inner socket/fd and dispatch the events yourself?

Does this work on Windows? Presumably you could just use TcpStream as the inner (if working with tcp of course).

Thanks!

**Comment by alexcrichton** [comment]
Indeed yeah you'd end up plumbing the object around like you would a `TcpStream` using it in the implementation of `Future` somewhere.

Unfortunately the `Evented` isn't implemented for custom types on Windows just yet because we haven't figured out the best way to expose custom IOCP yet. We'd like to of course leave the door open to it though!

**Comment by aajtodd** [comment]
Maybe I'm missing something, Windows has an implementation of [TcpStream](https://github.com/carllerche/mio/blob/9f17b70d6fecbf912168267ea74cf536f2cba705/src/sys/windows/tcp.rs#L404) that implements `Evented`

Wouldn't you just have something along the lines of:

``` rust
struct MyData {
    stream: PollEvented<SocketWrapper>,
}

struct SocketWrapper {
    inner: TcpStream
}

impl Evented for SocketWrapper {
     fn register(&self,
                poll: &mio::Poll,
                token: mio::Token,
                interest: mio::Ready,
                opts: mio::PollOpt) -> io::Result<()> 
     {
         self.inner.register(poll, token, interest, opts)
     }
     ...
}


impl Future for MyData {
    type Item = ();
    type Error = io::Error;

    fn poll(&mut self) -> Poll<(), io::Error> {
        if self.stream.poll_read().is_ready() {...}
    }
}
```

I can understand if this doesn't work on Windows for custom IOCP but it looks like it would work for Tcp or Udp right?

Thanks again Alex!

**Comment by alexcrichton** [comment]
Ah yeah you could definitely do that for Windows. I basically just meant that if you have a custom fd on Unix, like signalfd, you can register it. If you have a custom handle on Windows, though, like a named pipe, there's currently no way to register it with IOCP. 

If you can you TCP as a fallback though that's work great! I'm gonna close this issue in that case as I believe this is covered for now.
