### ISSUE TITLE
Consider splitting FramedIo -> FramedRead + FramedWrite

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#66]
... or maybe `ReadFrame` + `WriteFrame`

relates to #62

cc @Ralith

**Comment by aturon** [comment]
As part of this, reconsider the use-case for `poll_read`. Ideally, the split here is something like a `Future` plus a `Sink` (if/when the latter becomes part of the futures crate).

**Comment by aturon** [comment]
I don't think this is relevant any longer.

**Comment by carllerche** [comment]
To clarify, this basically happened by using `Sink + Stream`
