### ISSUE TITLE
FramedIo should return Option<Self::In> and maybe take Option<Self::Out>

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-core#67]
Need to signal EOF in `read` and may want to signal "shutdown" in `write`

**Comment by carllerche** [comment]
In the case of framing, EOF isn't simply the socket is shutdown. There is the "expected" shutdown when the protocol is at a point where it may cleanly be shutdown, and there are unexpected EOFs which are errors.

Also, the `FramedIo` needs to be able to signal "done" on read even if the underlying socket did not shutdown. In fact, the `FramedIo` may return "done" while the write half is open and there are still frames to write.

My current thought is that this should be left up to the protocol to determine how EOF should be signaled. If the protocol already includes end of protocol information in the frame type, having to then return `None` on the next read seems a bit unnecessary.

However, it may be that the pattern of including a "done" frame is common enough that requiring implementations to return `None` anyway is fine.

Either way, I think read & write should be symmetric, so if read takes `Option<T>` then write should as well.

**Comment by alexcrichton** [comment]
@aturon, @carllerche, and I discussed this the other day, and I believe these were our conclusions:

The remaining problem here is that a `Framed` object cannot be told that it will never be given another frame to write. Some protocols may take this into account and shutdown a TCP stream, for example, or otherwise have some form of graceful shutdown.

Our thinking though was that because `Framed` is just `Stream` and `Sink` that this is not so much a problem with `Framed` but rather a problem with `Sink`. That though has far reaching ramifications for what appears to be little benefit. It was originally considered to bake this into `Sink` to the decision later was to reflect this in the type of the item, not the trait itself.

In any case we also couldn't think of a great use case for where this would affect `Codec` either. The codec case is "easy mode" and shouldn't necessarily implement everything for you. Instead we felt that this feature (telling a sink that you're done writing) is best done at the transport layer going into tokio-proto.

We specifically discussed adding a method to `Transport` traits in tokio-proto to reflect that the transport is done receiving frames, triggering a graceful shutdown if necessary.

As a result of that I'm going to open an issue on tokio-proto to track this.
