### ISSUE TITLE
How to return futures generated from operating on a stream field?

### ISSUE THREAD

**Issue by spinda** [tokio-rs/tokio-core#70]
For example, say we have a `Client` struct that owns a `UnixStream`:

``` rust
pub struct Client {
    stream: UnixStream,
}
```

We implement a simple `hello` method on the `Client`:

``` rust
impl Client { 
   pub fn hello(&self) -> IoFuture<()> {
       write_all(&self.stream, "Hello!\r\n").map(|_| ()).boxed()
    }
}
```

This won't compile, because the future returned from `write_all` wants to hold onto the reference to `self.stream` longer than the reference to `self` is guaranteed to survive.

Is there a correct way of doing this?

**Comment by carllerche** [comment]
The client stream needs to pass ownership of the `UnixStream` to the `write_all` fn.

You can use an enum in `Client` to track the state:

``` rust
enum ClientState {
  Ready(UnixStream),
  Writing(WriteAll<UnixStream, &'static str>,
}
```

**Comment by spinda** [comment]
Ah ha, that's brilliant! Thanks.
