### ISSUE TITLE
FramedIo::write should borrow, not move, the input message

### ISSUE THREAD

**Issue by spinda** [tokio-rs/tokio-core#74]
Currently `FramedIo::write` is defined as follows:

``` rust
fn write(&mut self, req: Self::In) -> Poll<(), Error>
```

If you call `framed.write(msg)` and get back `Ok(Async::NotReady)`, there's no easy way to attempt retransmission: `msg` has already been moved and discarded by `write`. The only way I can see to avoid this is to make a wasteful copy of `msg` before every transmission attempt.

Can `req` be switched from `Self::In` to `&Self::In`?

**Comment by spinda** [comment]
`Serialize::serialize` would have to be changed to take a reference as well.

**Comment by carllerche** [comment]
The issue with `&Self::In` is that the `FramedIo` implementation needs to take ownership of the value in order to provide efficient implementations.

If the `FramedIo` is unable to process the write, the plan will be to return it to the caller in the error part of the `Result`: alexcrichton/futures-rs#213

**Comment by spinda** [comment]
> The issue with `&Self::In` is that the `FramedIo` implementation needs to take ownership of the value in order to provide efficient implementations.

Would you mind explaining why that is? I'm fairly new to Rust. I understand why functions that return `Future`s need to take ownership of their sources, but I don't see the reason here.

**Comment by carllerche** [comment]
The main reason is, because it is impossible to guarantee that the value can be written in its entirety, the FramedIo needs to be able to take owership of the value to finish writing it in the flush fn
