### ISSUE TITLE
Reconsider exposing `Vec<u8>` in `easy`

### ISSUE THREAD

**Issue by aturon** [tokio-rs/tokio-core#81]
Right now, representation details about `EasyBuf` are leaked, in particular the fact that it's ultimately backed by a `Vec<u8>` (which you can get immutable access to). We should probably hide these details.

**Comment by carllerche** [comment]
I believe that this issue should be closed as we are moving to tokio-io + bytes.

**Comment by alexcrichton** [comment]
Yeah I figured we'd close these out when the migration is performed.

**Comment by alexcrichton** [comment]
Er on second thought, let's actively clean out, I think we're good here with https://github.com/alexcrichton/tokio-io now
