### ISSUE TITLE
Using handle and boxed stream together

### ISSUE THREAD

**Issue by debris** [tokio-rs/tokio-core#85]
I've been stuck with this piece of code for about an hour...

This code is responsible for accepting incoming connections (it does handshake etc).

``` rust
pub fn listen(handle: &Handle, config: Config) -> Result<Listen, io::Error> {
    let listener = try!(TcpListener::bind(&config.local_address, handle));
    let listen = Listen {
        inner: listener.incoming()
            .and_then(move |(stream, address)| accept_connection(stream, &config, address))
            .boxed(),
    };
    Ok(listen)
}

pub struct Listen {
    inner: IoStream<MessageResult<Connection>>,
}
```

So far, so good, everything works fine. The problem starts when I try to create a timeout inisde my accept_connection function (using `tokio_core::reactor::Timeout`). After modifications my code looks like this:

``` rust
pub fn listen(handle: &Handle, config: Config) -> Result<Listen, io::Error> {
    let listener = try!(TcpListener::bind(&config.local_address, handle));
    let handle = handle.clone();
    let listen = Listen {
        inner: listener.incoming()
            .and_then(move |(stream, address)| accept_connection(stream, &handle, &config, address))
            .boxed(),
    };
    Ok(listen)
}

pub struct Listen {
    inner: IoStream<DeadlineStatus<MessageResult<Connection>>>,
}
```

So I've changed 3 lines:

``` diff
+   let handle = handle.clone();
-           .and_then(move |(stream, address)| accept_connection(stream, &config, address))
+           .and_then(move |(stream, address)| accept_connection(stream, &handle, &config, address))
-   inner: IoStream<MessageResult<Connection>>,
+   inner: IoStream<DeadlineStatus<MessageResult<Connection>>>,
```

Unfortunately, I'm no longer able to compile it:

```
  --> p2p/src/net/listen.rs:18:5
   |
18 |            .boxed(),
   |             ^^^^^
   |
   = note: `std::rc::Weak<std::cell::RefCell<tokio_core::reactor::Inner>>` cannot be sent between threads safely
   = note: required because it appears within the type `tokio_core::reactor::Handle`
   = note: required because it appears within the type `[closure@p2p/src/net/listen.rs:17:14: 17:91 handle:tokio_core::reactor::Handle, config:net::config::Config]`
   = note: required because it appears within the type `futures::stream::AndThen<tokio_core::net::Incoming, [closure@p2p/src/net/listen.rs:17:14: 17:91 handle:tokio_core::reactor::Handle, config:net::config::Config], io::deadline::Deadline<net::listen::AcceptConnection>>`
```

The error is very clear. I cannot box the stream, cause it needs to be `Send` while `rc::Weak` inside `Handle` is `!Send`.

So... how can I use handle iniside boxed stream to return something synchronously? :D It seems that I cannot :D

After few minutes of digging I realized that one thing which would help here (a lot!) is additional (or new version of) constructor for `tokio_core::reactor::Timeout`

``` rust
    pub fn new_at(at: Instant, handle: &Remote) -> io::Result<Timeout> {
```

**Comment by alexcrichton** [comment]
It looks like what's happening here is that a `Handle` is being stored somewhere that it should perhaps be a `Remote` instead. The `IoStream` type requires the stream is `Send + 'static`, but the `Handle` type is not `Send`. Does that ring any bells? The storage may be happening transitively through a closure I believe.

**Comment by alexcrichton** [comment]
Closing as I believe this is expected with storage of a `Handle`, but if that's not it feel free to resubmit!
