### ISSUE TITLE
`io::copy` should return ownership of the read / write handles

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#86]
It would be helpful to get the handles back to the `reader` / `writer` so that they can be used again later.

**Comment by dwrensha** [comment]
See #24, which includes such a change in a commit. Feel free to just pull in just that commit!

**Comment by alexcrichton** [comment]
👍

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io, the migration of this crate will be tracked by https://github.com/tokio-rs/tokio-core/issues/61
