### ISSUE TITLE
echo.rs example panics

### ISSUE THREAD

**Issue by k4rtik** [tokio-rs/tokio-core#96]
I am trying to find out if I can use `tokio-core` for implementing a TCP state machine for a school project.

While trying out the echo example with the following dependencies:
```
[dependencies]
tokio-core = "0.1"
env_logger = "*"
log = "*"
futures = "*"
```
and on trying to connect to the echo server using telnet, I see the following panic:
```
┌─[kartik][breogan][±][master U:1 ?:1 ✗][~/Projects/tokio-core/examples/echo]
└─▪ cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/echo`
Listening on: 127.0.0.1:8080
thread 'main' panicked at 'TaskRc being accessed on task it does not belong to', /home/kartik/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.3/src/lib.rs:209
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by k4rtik** [comment]
Looks like there is #31 reported for the same issue.

**Comment by dwrensha** [comment]
Heh, perhaps I was premature in submitting https://github.com/tokio-rs/tokio-core/pull/91. If you use the latest git master version of futures-rs and tokio-core, then the panics should go away.

**Comment by k4rtik** [comment]
@dwrensha thanks, working now with your suggestion.

**Comment by k4rtik** [comment]
Also, realized, I should have read the instructions at the top of `echo.rs` instead of creating a new project to run the example. That works as well.
