### ISSUE TITLE
Polling from Streams

### ISSUE THREAD

**Issue by jugglerchris** [tokio-rs/tokio-core#99]
I have a `Stream`, and want to expose a "get next item" API.  I'm currently doing something involving an `Option` so that I can temporarily take the `Stream` out, convert it into a future, run it to get the value and "rest of stream", and put the latter back in:

```rust
enum Event { ... }
struct Foo {
    core: Core,
    events: Option<IoStream<Event>>,
}

impl Foo {
    pub fn get_next_event(&mut self) -> Event {
        let mut events = self.events.take().unwrap();
        let evt = match self.core.run(events.into_future()) {
            Ok((Some(evt), rest)) => {
                 self.events = Some(rest);
                 evt
            },
            // error cases
        }
    }
}
```

This basically works but seems awkward.  I'm sure I'm missing something, but would it make sense to have a function like `Core::run` but which takes an `&mut Stream` instead of `Future` and returns the next result from the stream?

**Comment by alexcrichton** [comment]
I believe `&mut Stream` implements `Stream`, so could this be:

``` rust
let events = &mut self.events;
let ret = self.core.run(events.into_future());
```

That way you never have to move in and out.

**Comment by jugglerchris** [comment]
Ah, that's what I was missing.  Thanks!
